// float_table writes the table of the powers of ten of shortestDecimal ( internal/floatfmt/float_table.go ): for each k
// from floatKMin to floatKMax, g = ⌊10⁻ᵏ·2¹²⁵⁻ᶠ⌋ + 1, where f = ⌊−k·log₂10⌋ as floorLog2Pow10 computes it, so that
// 2¹²⁵ ≤ g < 2¹²⁶, as its high 63 bits and its low 63 bits.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"math/big"
	"os"
)

const (
	kMin = -324
	kMax = 292
)

func floorLog2Pow10(e int) int { return int(int64(e) * 913124641741 >> 38) }

func main() {
	out := "internal/floatfmt/float_table.go"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/cmd/float_table. DO NOT EDIT.\n\npackage floatfmt\n\n")
	b.WriteString("// floatPow10 are the pairs of the high and the low 63 bits of the powers of ten of shortestDecimal, from\n")
	b.WriteString("// floatKMin to floatKMax.\n")
	fmt.Fprintf(&b, "var floatPow10 = [%d][2]uint64{\n", kMax-kMin+1)
	mask := new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 63), big.NewInt(1))
	for k := kMin; k <= kMax; k++ {
		shift := 125 - floorLog2Pow10(-k)
		num, den := big.NewInt(1), big.NewInt(1)
		ten := new(big.Int).Exp(big.NewInt(10), big.NewInt(int64(abs(k))), nil)
		if k <= 0 {
			num.Set(ten)
		} else {
			den.Set(ten)
		}
		if shift >= 0 {
			num.Lsh(num, uint(shift))
		} else {
			den.Lsh(den, uint(-shift))
		}
		g := new(big.Int).Quo(num, den)
		g.Add(g, big.NewInt(1))
		if g.BitLen() != 126 {
			panic(fmt.Sprintf("g of %d has %d bits", k, g.BitLen()))
		}
		hi := new(big.Int).Rsh(g, 63)
		lo := new(big.Int).And(g, mask)
		fmt.Fprintf(&b, "\t{%#016x, %#016x}, // %d\n", hi.Uint64(), lo.Uint64(), k)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(out, src, 0o644); err != nil {
		panic(err)
	}
}

func abs(k int) int {
	if k < 0 {
		return -k
	}
	return k
}
