version: "2"
linters:
  default: all
  disable:
    - asciicheck
    - containedctx
    - cyclop
    - depguard
    - dogsled
    - dupl
    - embeddedstructfieldcheck
    - err113
    - errchkjson
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosmopolitan
    - gosec
    - govet
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - makezero
    - mirror
    - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - paralleltest
    - perfsprint
    - predeclared
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - unconvert
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    govet:
      disable:
        - shadow
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: /*.go
        text: 'ST1003: should not use underscores in package names'
      - linters:
          - golint
        path: /*.go
        text: don't use an underscore in package name
      - linters:
          - golint
          - staticcheck
        path: rtype.go
      - linters:
          - staticcheck
        path: error.go
      - linters:
          - godoclint
        path: internal/encoder/int.go
      - linters:
          - godoclint
        path: internal/encoder/string.go
      - linters:
          - godoclint
        path: internal/encoder/encoder.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - ".*_test.go"
      - test/
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - ".*_test.go"
      - test/
