// Code generated by cmd/generator. DO NOT EDIT!
package json

import (
	"strings"
)

type codeType int

const (
	codeOp                   codeType = 0
	codeArrayHead            codeType = 1
	codeArrayElem            codeType = 2
	codeSliceHead            codeType = 3
	codeSliceElem            codeType = 4
	codeMapHead              codeType = 5
	codeMapKey               codeType = 6
	codeMapValue             codeType = 7
	codeMapEnd               codeType = 8
	codeStructFieldRecursive codeType = 9
	codeStructField          codeType = 10
	codeStructEnd            codeType = 11
)

var opTypeStrings = [893]string{
	"End",
	"Interface",
	"Ptr",
	"NPtr",
	"SliceHead",
	"RootSliceHead",
	"SliceElem",
	"RootSliceElem",
	"SliceEnd",
	"ArrayHead",
	"ArrayElem",
	"ArrayEnd",
	"MapHead",
	"MapHeadLoad",
	"MapKey",
	"MapValue",
	"MapEnd",
	"StructFieldRecursiveEnd",
	"StructAnonymousEnd",
	"Int",
	"Uint",
	"Float32",
	"Float64",
	"Bool",
	"String",
	"Bytes",
	"Array",
	"Map",
	"MapLoad",
	"Slice",
	"Struct",
	"MarshalJSON",
	"MarshalText",
	"Recursive",
	"IntString",
	"UintString",
	"IntPtr",
	"UintPtr",
	"Float32Ptr",
	"Float64Ptr",
	"BoolPtr",
	"StringPtr",
	"BytesPtr",
	"ArrayPtr",
	"SlicePtr",
	"MapPtr",
	"IntNPtr",
	"UintNPtr",
	"Float32NPtr",
	"Float64NPtr",
	"BoolNPtr",
	"StringNPtr",
	"BytesNPtr",
	"StructFieldHeadInt",
	"StructFieldHeadOmitEmptyInt",
	"StructFieldHeadStringTagInt",
	"StructFieldAnonymousHeadInt",
	"StructFieldAnonymousHeadOmitEmptyInt",
	"StructFieldAnonymousHeadStringTagInt",
	"StructFieldPtrHeadInt",
	"StructFieldPtrHeadOmitEmptyInt",
	"StructFieldPtrHeadStringTagInt",
	"StructFieldPtrAnonymousHeadInt",
	"StructFieldPtrAnonymousHeadOmitEmptyInt",
	"StructFieldPtrAnonymousHeadStringTagInt",
	"StructFieldNPtrHeadInt",
	"StructFieldNPtrHeadOmitEmptyInt",
	"StructFieldNPtrHeadStringTagInt",
	"StructFieldNPtrAnonymousHeadInt",
	"StructFieldNPtrAnonymousHeadOmitEmptyInt",
	"StructFieldNPtrAnonymousHeadStringTagInt",
	"StructFieldHeadUint",
	"StructFieldHeadOmitEmptyUint",
	"StructFieldHeadStringTagUint",
	"StructFieldAnonymousHeadUint",
	"StructFieldAnonymousHeadOmitEmptyUint",
	"StructFieldAnonymousHeadStringTagUint",
	"StructFieldPtrHeadUint",
	"StructFieldPtrHeadOmitEmptyUint",
	"StructFieldPtrHeadStringTagUint",
	"StructFieldPtrAnonymousHeadUint",
	"StructFieldPtrAnonymousHeadOmitEmptyUint",
	"StructFieldPtrAnonymousHeadStringTagUint",
	"StructFieldNPtrHeadUint",
	"StructFieldNPtrHeadOmitEmptyUint",
	"StructFieldNPtrHeadStringTagUint",
	"StructFieldNPtrAnonymousHeadUint",
	"StructFieldNPtrAnonymousHeadOmitEmptyUint",
	"StructFieldNPtrAnonymousHeadStringTagUint",
	"StructFieldHeadFloat32",
	"StructFieldHeadOmitEmptyFloat32",
	"StructFieldHeadStringTagFloat32",
	"StructFieldAnonymousHeadFloat32",
	"StructFieldAnonymousHeadOmitEmptyFloat32",
	"StructFieldAnonymousHeadStringTagFloat32",
	"StructFieldPtrHeadFloat32",
	"StructFieldPtrHeadOmitEmptyFloat32",
	"StructFieldPtrHeadStringTagFloat32",
	"StructFieldPtrAnonymousHeadFloat32",
	"StructFieldPtrAnonymousHeadOmitEmptyFloat32",
	"StructFieldPtrAnonymousHeadStringTagFloat32",
	"StructFieldNPtrHeadFloat32",
	"StructFieldNPtrHeadOmitEmptyFloat32",
	"StructFieldNPtrHeadStringTagFloat32",
	"StructFieldNPtrAnonymousHeadFloat32",
	"StructFieldNPtrAnonymousHeadOmitEmptyFloat32",
	"StructFieldNPtrAnonymousHeadStringTagFloat32",
	"StructFieldHeadFloat64",
	"StructFieldHeadOmitEmptyFloat64",
	"StructFieldHeadStringTagFloat64",
	"StructFieldAnonymousHeadFloat64",
	"StructFieldAnonymousHeadOmitEmptyFloat64",
	"StructFieldAnonymousHeadStringTagFloat64",
	"StructFieldPtrHeadFloat64",
	"StructFieldPtrHeadOmitEmptyFloat64",
	"StructFieldPtrHeadStringTagFloat64",
	"StructFieldPtrAnonymousHeadFloat64",
	"StructFieldPtrAnonymousHeadOmitEmptyFloat64",
	"StructFieldPtrAnonymousHeadStringTagFloat64",
	"StructFieldNPtrHeadFloat64",
	"StructFieldNPtrHeadOmitEmptyFloat64",
	"StructFieldNPtrHeadStringTagFloat64",
	"StructFieldNPtrAnonymousHeadFloat64",
	"StructFieldNPtrAnonymousHeadOmitEmptyFloat64",
	"StructFieldNPtrAnonymousHeadStringTagFloat64",
	"StructFieldHeadBool",
	"StructFieldHeadOmitEmptyBool",
	"StructFieldHeadStringTagBool",
	"StructFieldAnonymousHeadBool",
	"StructFieldAnonymousHeadOmitEmptyBool",
	"StructFieldAnonymousHeadStringTagBool",
	"StructFieldPtrHeadBool",
	"StructFieldPtrHeadOmitEmptyBool",
	"StructFieldPtrHeadStringTagBool",
	"StructFieldPtrAnonymousHeadBool",
	"StructFieldPtrAnonymousHeadOmitEmptyBool",
	"StructFieldPtrAnonymousHeadStringTagBool",
	"StructFieldNPtrHeadBool",
	"StructFieldNPtrHeadOmitEmptyBool",
	"StructFieldNPtrHeadStringTagBool",
	"StructFieldNPtrAnonymousHeadBool",
	"StructFieldNPtrAnonymousHeadOmitEmptyBool",
	"StructFieldNPtrAnonymousHeadStringTagBool",
	"StructFieldHeadString",
	"StructFieldHeadOmitEmptyString",
	"StructFieldHeadStringTagString",
	"StructFieldAnonymousHeadString",
	"StructFieldAnonymousHeadOmitEmptyString",
	"StructFieldAnonymousHeadStringTagString",
	"StructFieldPtrHeadString",
	"StructFieldPtrHeadOmitEmptyString",
	"StructFieldPtrHeadStringTagString",
	"StructFieldPtrAnonymousHeadString",
	"StructFieldPtrAnonymousHeadOmitEmptyString",
	"StructFieldPtrAnonymousHeadStringTagString",
	"StructFieldNPtrHeadString",
	"StructFieldNPtrHeadOmitEmptyString",
	"StructFieldNPtrHeadStringTagString",
	"StructFieldNPtrAnonymousHeadString",
	"StructFieldNPtrAnonymousHeadOmitEmptyString",
	"StructFieldNPtrAnonymousHeadStringTagString",
	"StructFieldHeadBytes",
	"StructFieldHeadOmitEmptyBytes",
	"StructFieldHeadStringTagBytes",
	"StructFieldAnonymousHeadBytes",
	"StructFieldAnonymousHeadOmitEmptyBytes",
	"StructFieldAnonymousHeadStringTagBytes",
	"StructFieldPtrHeadBytes",
	"StructFieldPtrHeadOmitEmptyBytes",
	"StructFieldPtrHeadStringTagBytes",
	"StructFieldPtrAnonymousHeadBytes",
	"StructFieldPtrAnonymousHeadOmitEmptyBytes",
	"StructFieldPtrAnonymousHeadStringTagBytes",
	"StructFieldNPtrHeadBytes",
	"StructFieldNPtrHeadOmitEmptyBytes",
	"StructFieldNPtrHeadStringTagBytes",
	"StructFieldNPtrAnonymousHeadBytes",
	"StructFieldNPtrAnonymousHeadOmitEmptyBytes",
	"StructFieldNPtrAnonymousHeadStringTagBytes",
	"StructFieldHeadArray",
	"StructFieldHeadOmitEmptyArray",
	"StructFieldHeadStringTagArray",
	"StructFieldAnonymousHeadArray",
	"StructFieldAnonymousHeadOmitEmptyArray",
	"StructFieldAnonymousHeadStringTagArray",
	"StructFieldPtrHeadArray",
	"StructFieldPtrHeadOmitEmptyArray",
	"StructFieldPtrHeadStringTagArray",
	"StructFieldPtrAnonymousHeadArray",
	"StructFieldPtrAnonymousHeadOmitEmptyArray",
	"StructFieldPtrAnonymousHeadStringTagArray",
	"StructFieldNPtrHeadArray",
	"StructFieldNPtrHeadOmitEmptyArray",
	"StructFieldNPtrHeadStringTagArray",
	"StructFieldNPtrAnonymousHeadArray",
	"StructFieldNPtrAnonymousHeadOmitEmptyArray",
	"StructFieldNPtrAnonymousHeadStringTagArray",
	"StructFieldHeadMap",
	"StructFieldHeadOmitEmptyMap",
	"StructFieldHeadStringTagMap",
	"StructFieldAnonymousHeadMap",
	"StructFieldAnonymousHeadOmitEmptyMap",
	"StructFieldAnonymousHeadStringTagMap",
	"StructFieldPtrHeadMap",
	"StructFieldPtrHeadOmitEmptyMap",
	"StructFieldPtrHeadStringTagMap",
	"StructFieldPtrAnonymousHeadMap",
	"StructFieldPtrAnonymousHeadOmitEmptyMap",
	"StructFieldPtrAnonymousHeadStringTagMap",
	"StructFieldNPtrHeadMap",
	"StructFieldNPtrHeadOmitEmptyMap",
	"StructFieldNPtrHeadStringTagMap",
	"StructFieldNPtrAnonymousHeadMap",
	"StructFieldNPtrAnonymousHeadOmitEmptyMap",
	"StructFieldNPtrAnonymousHeadStringTagMap",
	"StructFieldHeadMapLoad",
	"StructFieldHeadOmitEmptyMapLoad",
	"StructFieldHeadStringTagMapLoad",
	"StructFieldAnonymousHeadMapLoad",
	"StructFieldAnonymousHeadOmitEmptyMapLoad",
	"StructFieldAnonymousHeadStringTagMapLoad",
	"StructFieldPtrHeadMapLoad",
	"StructFieldPtrHeadOmitEmptyMapLoad",
	"StructFieldPtrHeadStringTagMapLoad",
	"StructFieldPtrAnonymousHeadMapLoad",
	"StructFieldPtrAnonymousHeadOmitEmptyMapLoad",
	"StructFieldPtrAnonymousHeadStringTagMapLoad",
	"StructFieldNPtrHeadMapLoad",
	"StructFieldNPtrHeadOmitEmptyMapLoad",
	"StructFieldNPtrHeadStringTagMapLoad",
	"StructFieldNPtrAnonymousHeadMapLoad",
	"StructFieldNPtrAnonymousHeadOmitEmptyMapLoad",
	"StructFieldNPtrAnonymousHeadStringTagMapLoad",
	"StructFieldHeadSlice",
	"StructFieldHeadOmitEmptySlice",
	"StructFieldHeadStringTagSlice",
	"StructFieldAnonymousHeadSlice",
	"StructFieldAnonymousHeadOmitEmptySlice",
	"StructFieldAnonymousHeadStringTagSlice",
	"StructFieldPtrHeadSlice",
	"StructFieldPtrHeadOmitEmptySlice",
	"StructFieldPtrHeadStringTagSlice",
	"StructFieldPtrAnonymousHeadSlice",
	"StructFieldPtrAnonymousHeadOmitEmptySlice",
	"StructFieldPtrAnonymousHeadStringTagSlice",
	"StructFieldNPtrHeadSlice",
	"StructFieldNPtrHeadOmitEmptySlice",
	"StructFieldNPtrHeadStringTagSlice",
	"StructFieldNPtrAnonymousHeadSlice",
	"StructFieldNPtrAnonymousHeadOmitEmptySlice",
	"StructFieldNPtrAnonymousHeadStringTagSlice",
	"StructFieldHeadStruct",
	"StructFieldHeadOmitEmptyStruct",
	"StructFieldHeadStringTagStruct",
	"StructFieldAnonymousHeadStruct",
	"StructFieldAnonymousHeadOmitEmptyStruct",
	"StructFieldAnonymousHeadStringTagStruct",
	"StructFieldPtrHeadStruct",
	"StructFieldPtrHeadOmitEmptyStruct",
	"StructFieldPtrHeadStringTagStruct",
	"StructFieldPtrAnonymousHeadStruct",
	"StructFieldPtrAnonymousHeadOmitEmptyStruct",
	"StructFieldPtrAnonymousHeadStringTagStruct",
	"StructFieldNPtrHeadStruct",
	"StructFieldNPtrHeadOmitEmptyStruct",
	"StructFieldNPtrHeadStringTagStruct",
	"StructFieldNPtrAnonymousHeadStruct",
	"StructFieldNPtrAnonymousHeadOmitEmptyStruct",
	"StructFieldNPtrAnonymousHeadStringTagStruct",
	"StructFieldHeadMarshalJSON",
	"StructFieldHeadOmitEmptyMarshalJSON",
	"StructFieldHeadStringTagMarshalJSON",
	"StructFieldAnonymousHeadMarshalJSON",
	"StructFieldAnonymousHeadOmitEmptyMarshalJSON",
	"StructFieldAnonymousHeadStringTagMarshalJSON",
	"StructFieldPtrHeadMarshalJSON",
	"StructFieldPtrHeadOmitEmptyMarshalJSON",
	"StructFieldPtrHeadStringTagMarshalJSON",
	"StructFieldPtrAnonymousHeadMarshalJSON",
	"StructFieldPtrAnonymousHeadOmitEmptyMarshalJSON",
	"StructFieldPtrAnonymousHeadStringTagMarshalJSON",
	"StructFieldNPtrHeadMarshalJSON",
	"StructFieldNPtrHeadOmitEmptyMarshalJSON",
	"StructFieldNPtrHeadStringTagMarshalJSON",
	"StructFieldNPtrAnonymousHeadMarshalJSON",
	"StructFieldNPtrAnonymousHeadOmitEmptyMarshalJSON",
	"StructFieldNPtrAnonymousHeadStringTagMarshalJSON",
	"StructFieldHeadMarshalText",
	"StructFieldHeadOmitEmptyMarshalText",
	"StructFieldHeadStringTagMarshalText",
	"StructFieldAnonymousHeadMarshalText",
	"StructFieldAnonymousHeadOmitEmptyMarshalText",
	"StructFieldAnonymousHeadStringTagMarshalText",
	"StructFieldPtrHeadMarshalText",
	"StructFieldPtrHeadOmitEmptyMarshalText",
	"StructFieldPtrHeadStringTagMarshalText",
	"StructFieldPtrAnonymousHeadMarshalText",
	"StructFieldPtrAnonymousHeadOmitEmptyMarshalText",
	"StructFieldPtrAnonymousHeadStringTagMarshalText",
	"StructFieldNPtrHeadMarshalText",
	"StructFieldNPtrHeadOmitEmptyMarshalText",
	"StructFieldNPtrHeadStringTagMarshalText",
	"StructFieldNPtrAnonymousHeadMarshalText",
	"StructFieldNPtrAnonymousHeadOmitEmptyMarshalText",
	"StructFieldNPtrAnonymousHeadStringTagMarshalText",
	"StructFieldHeadRecursive",
	"StructFieldHeadOmitEmptyRecursive",
	"StructFieldHeadStringTagRecursive",
	"StructFieldAnonymousHeadRecursive",
	"StructFieldAnonymousHeadOmitEmptyRecursive",
	"StructFieldAnonymousHeadStringTagRecursive",
	"StructFieldPtrHeadRecursive",
	"StructFieldPtrHeadOmitEmptyRecursive",
	"StructFieldPtrHeadStringTagRecursive",
	"StructFieldPtrAnonymousHeadRecursive",
	"StructFieldPtrAnonymousHeadOmitEmptyRecursive",
	"StructFieldPtrAnonymousHeadStringTagRecursive",
	"StructFieldNPtrHeadRecursive",
	"StructFieldNPtrHeadOmitEmptyRecursive",
	"StructFieldNPtrHeadStringTagRecursive",
	"StructFieldNPtrAnonymousHeadRecursive",
	"StructFieldNPtrAnonymousHeadOmitEmptyRecursive",
	"StructFieldNPtrAnonymousHeadStringTagRecursive",
	"StructFieldHeadIntString",
	"StructFieldHeadOmitEmptyIntString",
	"StructFieldHeadStringTagIntString",
	"StructFieldAnonymousHeadIntString",
	"StructFieldAnonymousHeadOmitEmptyIntString",
	"StructFieldAnonymousHeadStringTagIntString",
	"StructFieldPtrHeadIntString",
	"StructFieldPtrHeadOmitEmptyIntString",
	"StructFieldPtrHeadStringTagIntString",
	"StructFieldPtrAnonymousHeadIntString",
	"StructFieldPtrAnonymousHeadOmitEmptyIntString",
	"StructFieldPtrAnonymousHeadStringTagIntString",
	"StructFieldNPtrHeadIntString",
	"StructFieldNPtrHeadOmitEmptyIntString",
	"StructFieldNPtrHeadStringTagIntString",
	"StructFieldNPtrAnonymousHeadIntString",
	"StructFieldNPtrAnonymousHeadOmitEmptyIntString",
	"StructFieldNPtrAnonymousHeadStringTagIntString",
	"StructFieldHeadUintString",
	"StructFieldHeadOmitEmptyUintString",
	"StructFieldHeadStringTagUintString",
	"StructFieldAnonymousHeadUintString",
	"StructFieldAnonymousHeadOmitEmptyUintString",
	"StructFieldAnonymousHeadStringTagUintString",
	"StructFieldPtrHeadUintString",
	"StructFieldPtrHeadOmitEmptyUintString",
	"StructFieldPtrHeadStringTagUintString",
	"StructFieldPtrAnonymousHeadUintString",
	"StructFieldPtrAnonymousHeadOmitEmptyUintString",
	"StructFieldPtrAnonymousHeadStringTagUintString",
	"StructFieldNPtrHeadUintString",
	"StructFieldNPtrHeadOmitEmptyUintString",
	"StructFieldNPtrHeadStringTagUintString",
	"StructFieldNPtrAnonymousHeadUintString",
	"StructFieldNPtrAnonymousHeadOmitEmptyUintString",
	"StructFieldNPtrAnonymousHeadStringTagUintString",
	"StructFieldHeadIntPtr",
	"StructFieldHeadOmitEmptyIntPtr",
	"StructFieldHeadStringTagIntPtr",
	"StructFieldAnonymousHeadIntPtr",
	"StructFieldAnonymousHeadOmitEmptyIntPtr",
	"StructFieldAnonymousHeadStringTagIntPtr",
	"StructFieldPtrHeadIntPtr",
	"StructFieldPtrHeadOmitEmptyIntPtr",
	"StructFieldPtrHeadStringTagIntPtr",
	"StructFieldPtrAnonymousHeadIntPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyIntPtr",
	"StructFieldPtrAnonymousHeadStringTagIntPtr",
	"StructFieldNPtrHeadIntPtr",
	"StructFieldNPtrHeadOmitEmptyIntPtr",
	"StructFieldNPtrHeadStringTagIntPtr",
	"StructFieldNPtrAnonymousHeadIntPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyIntPtr",
	"StructFieldNPtrAnonymousHeadStringTagIntPtr",
	"StructFieldHeadUintPtr",
	"StructFieldHeadOmitEmptyUintPtr",
	"StructFieldHeadStringTagUintPtr",
	"StructFieldAnonymousHeadUintPtr",
	"StructFieldAnonymousHeadOmitEmptyUintPtr",
	"StructFieldAnonymousHeadStringTagUintPtr",
	"StructFieldPtrHeadUintPtr",
	"StructFieldPtrHeadOmitEmptyUintPtr",
	"StructFieldPtrHeadStringTagUintPtr",
	"StructFieldPtrAnonymousHeadUintPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyUintPtr",
	"StructFieldPtrAnonymousHeadStringTagUintPtr",
	"StructFieldNPtrHeadUintPtr",
	"StructFieldNPtrHeadOmitEmptyUintPtr",
	"StructFieldNPtrHeadStringTagUintPtr",
	"StructFieldNPtrAnonymousHeadUintPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyUintPtr",
	"StructFieldNPtrAnonymousHeadStringTagUintPtr",
	"StructFieldHeadFloat32Ptr",
	"StructFieldHeadOmitEmptyFloat32Ptr",
	"StructFieldHeadStringTagFloat32Ptr",
	"StructFieldAnonymousHeadFloat32Ptr",
	"StructFieldAnonymousHeadOmitEmptyFloat32Ptr",
	"StructFieldAnonymousHeadStringTagFloat32Ptr",
	"StructFieldPtrHeadFloat32Ptr",
	"StructFieldPtrHeadOmitEmptyFloat32Ptr",
	"StructFieldPtrHeadStringTagFloat32Ptr",
	"StructFieldPtrAnonymousHeadFloat32Ptr",
	"StructFieldPtrAnonymousHeadOmitEmptyFloat32Ptr",
	"StructFieldPtrAnonymousHeadStringTagFloat32Ptr",
	"StructFieldNPtrHeadFloat32Ptr",
	"StructFieldNPtrHeadOmitEmptyFloat32Ptr",
	"StructFieldNPtrHeadStringTagFloat32Ptr",
	"StructFieldNPtrAnonymousHeadFloat32Ptr",
	"StructFieldNPtrAnonymousHeadOmitEmptyFloat32Ptr",
	"StructFieldNPtrAnonymousHeadStringTagFloat32Ptr",
	"StructFieldHeadFloat64Ptr",
	"StructFieldHeadOmitEmptyFloat64Ptr",
	"StructFieldHeadStringTagFloat64Ptr",
	"StructFieldAnonymousHeadFloat64Ptr",
	"StructFieldAnonymousHeadOmitEmptyFloat64Ptr",
	"StructFieldAnonymousHeadStringTagFloat64Ptr",
	"StructFieldPtrHeadFloat64Ptr",
	"StructFieldPtrHeadOmitEmptyFloat64Ptr",
	"StructFieldPtrHeadStringTagFloat64Ptr",
	"StructFieldPtrAnonymousHeadFloat64Ptr",
	"StructFieldPtrAnonymousHeadOmitEmptyFloat64Ptr",
	"StructFieldPtrAnonymousHeadStringTagFloat64Ptr",
	"StructFieldNPtrHeadFloat64Ptr",
	"StructFieldNPtrHeadOmitEmptyFloat64Ptr",
	"StructFieldNPtrHeadStringTagFloat64Ptr",
	"StructFieldNPtrAnonymousHeadFloat64Ptr",
	"StructFieldNPtrAnonymousHeadOmitEmptyFloat64Ptr",
	"StructFieldNPtrAnonymousHeadStringTagFloat64Ptr",
	"StructFieldHeadBoolPtr",
	"StructFieldHeadOmitEmptyBoolPtr",
	"StructFieldHeadStringTagBoolPtr",
	"StructFieldAnonymousHeadBoolPtr",
	"StructFieldAnonymousHeadOmitEmptyBoolPtr",
	"StructFieldAnonymousHeadStringTagBoolPtr",
	"StructFieldPtrHeadBoolPtr",
	"StructFieldPtrHeadOmitEmptyBoolPtr",
	"StructFieldPtrHeadStringTagBoolPtr",
	"StructFieldPtrAnonymousHeadBoolPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyBoolPtr",
	"StructFieldPtrAnonymousHeadStringTagBoolPtr",
	"StructFieldNPtrHeadBoolPtr",
	"StructFieldNPtrHeadOmitEmptyBoolPtr",
	"StructFieldNPtrHeadStringTagBoolPtr",
	"StructFieldNPtrAnonymousHeadBoolPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyBoolPtr",
	"StructFieldNPtrAnonymousHeadStringTagBoolPtr",
	"StructFieldHeadStringPtr",
	"StructFieldHeadOmitEmptyStringPtr",
	"StructFieldHeadStringTagStringPtr",
	"StructFieldAnonymousHeadStringPtr",
	"StructFieldAnonymousHeadOmitEmptyStringPtr",
	"StructFieldAnonymousHeadStringTagStringPtr",
	"StructFieldPtrHeadStringPtr",
	"StructFieldPtrHeadOmitEmptyStringPtr",
	"StructFieldPtrHeadStringTagStringPtr",
	"StructFieldPtrAnonymousHeadStringPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyStringPtr",
	"StructFieldPtrAnonymousHeadStringTagStringPtr",
	"StructFieldNPtrHeadStringPtr",
	"StructFieldNPtrHeadOmitEmptyStringPtr",
	"StructFieldNPtrHeadStringTagStringPtr",
	"StructFieldNPtrAnonymousHeadStringPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyStringPtr",
	"StructFieldNPtrAnonymousHeadStringTagStringPtr",
	"StructFieldHeadBytesPtr",
	"StructFieldHeadOmitEmptyBytesPtr",
	"StructFieldHeadStringTagBytesPtr",
	"StructFieldAnonymousHeadBytesPtr",
	"StructFieldAnonymousHeadOmitEmptyBytesPtr",
	"StructFieldAnonymousHeadStringTagBytesPtr",
	"StructFieldPtrHeadBytesPtr",
	"StructFieldPtrHeadOmitEmptyBytesPtr",
	"StructFieldPtrHeadStringTagBytesPtr",
	"StructFieldPtrAnonymousHeadBytesPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyBytesPtr",
	"StructFieldPtrAnonymousHeadStringTagBytesPtr",
	"StructFieldNPtrHeadBytesPtr",
	"StructFieldNPtrHeadOmitEmptyBytesPtr",
	"StructFieldNPtrHeadStringTagBytesPtr",
	"StructFieldNPtrAnonymousHeadBytesPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyBytesPtr",
	"StructFieldNPtrAnonymousHeadStringTagBytesPtr",
	"StructFieldHeadArrayPtr",
	"StructFieldHeadOmitEmptyArrayPtr",
	"StructFieldHeadStringTagArrayPtr",
	"StructFieldAnonymousHeadArrayPtr",
	"StructFieldAnonymousHeadOmitEmptyArrayPtr",
	"StructFieldAnonymousHeadStringTagArrayPtr",
	"StructFieldPtrHeadArrayPtr",
	"StructFieldPtrHeadOmitEmptyArrayPtr",
	"StructFieldPtrHeadStringTagArrayPtr",
	"StructFieldPtrAnonymousHeadArrayPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyArrayPtr",
	"StructFieldPtrAnonymousHeadStringTagArrayPtr",
	"StructFieldNPtrHeadArrayPtr",
	"StructFieldNPtrHeadOmitEmptyArrayPtr",
	"StructFieldNPtrHeadStringTagArrayPtr",
	"StructFieldNPtrAnonymousHeadArrayPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyArrayPtr",
	"StructFieldNPtrAnonymousHeadStringTagArrayPtr",
	"StructFieldHeadSlicePtr",
	"StructFieldHeadOmitEmptySlicePtr",
	"StructFieldHeadStringTagSlicePtr",
	"StructFieldAnonymousHeadSlicePtr",
	"StructFieldAnonymousHeadOmitEmptySlicePtr",
	"StructFieldAnonymousHeadStringTagSlicePtr",
	"StructFieldPtrHeadSlicePtr",
	"StructFieldPtrHeadOmitEmptySlicePtr",
	"StructFieldPtrHeadStringTagSlicePtr",
	"StructFieldPtrAnonymousHeadSlicePtr",
	"StructFieldPtrAnonymousHeadOmitEmptySlicePtr",
	"StructFieldPtrAnonymousHeadStringTagSlicePtr",
	"StructFieldNPtrHeadSlicePtr",
	"StructFieldNPtrHeadOmitEmptySlicePtr",
	"StructFieldNPtrHeadStringTagSlicePtr",
	"StructFieldNPtrAnonymousHeadSlicePtr",
	"StructFieldNPtrAnonymousHeadOmitEmptySlicePtr",
	"StructFieldNPtrAnonymousHeadStringTagSlicePtr",
	"StructFieldHeadMapPtr",
	"StructFieldHeadOmitEmptyMapPtr",
	"StructFieldHeadStringTagMapPtr",
	"StructFieldAnonymousHeadMapPtr",
	"StructFieldAnonymousHeadOmitEmptyMapPtr",
	"StructFieldAnonymousHeadStringTagMapPtr",
	"StructFieldPtrHeadMapPtr",
	"StructFieldPtrHeadOmitEmptyMapPtr",
	"StructFieldPtrHeadStringTagMapPtr",
	"StructFieldPtrAnonymousHeadMapPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyMapPtr",
	"StructFieldPtrAnonymousHeadStringTagMapPtr",
	"StructFieldNPtrHeadMapPtr",
	"StructFieldNPtrHeadOmitEmptyMapPtr",
	"StructFieldNPtrHeadStringTagMapPtr",
	"StructFieldNPtrAnonymousHeadMapPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyMapPtr",
	"StructFieldNPtrAnonymousHeadStringTagMapPtr",
	"StructFieldHeadIntNPtr",
	"StructFieldHeadOmitEmptyIntNPtr",
	"StructFieldHeadStringTagIntNPtr",
	"StructFieldAnonymousHeadIntNPtr",
	"StructFieldAnonymousHeadOmitEmptyIntNPtr",
	"StructFieldAnonymousHeadStringTagIntNPtr",
	"StructFieldPtrHeadIntNPtr",
	"StructFieldPtrHeadOmitEmptyIntNPtr",
	"StructFieldPtrHeadStringTagIntNPtr",
	"StructFieldPtrAnonymousHeadIntNPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyIntNPtr",
	"StructFieldPtrAnonymousHeadStringTagIntNPtr",
	"StructFieldNPtrHeadIntNPtr",
	"StructFieldNPtrHeadOmitEmptyIntNPtr",
	"StructFieldNPtrHeadStringTagIntNPtr",
	"StructFieldNPtrAnonymousHeadIntNPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyIntNPtr",
	"StructFieldNPtrAnonymousHeadStringTagIntNPtr",
	"StructFieldHeadUintNPtr",
	"StructFieldHeadOmitEmptyUintNPtr",
	"StructFieldHeadStringTagUintNPtr",
	"StructFieldAnonymousHeadUintNPtr",
	"StructFieldAnonymousHeadOmitEmptyUintNPtr",
	"StructFieldAnonymousHeadStringTagUintNPtr",
	"StructFieldPtrHeadUintNPtr",
	"StructFieldPtrHeadOmitEmptyUintNPtr",
	"StructFieldPtrHeadStringTagUintNPtr",
	"StructFieldPtrAnonymousHeadUintNPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyUintNPtr",
	"StructFieldPtrAnonymousHeadStringTagUintNPtr",
	"StructFieldNPtrHeadUintNPtr",
	"StructFieldNPtrHeadOmitEmptyUintNPtr",
	"StructFieldNPtrHeadStringTagUintNPtr",
	"StructFieldNPtrAnonymousHeadUintNPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyUintNPtr",
	"StructFieldNPtrAnonymousHeadStringTagUintNPtr",
	"StructFieldHeadFloat32NPtr",
	"StructFieldHeadOmitEmptyFloat32NPtr",
	"StructFieldHeadStringTagFloat32NPtr",
	"StructFieldAnonymousHeadFloat32NPtr",
	"StructFieldAnonymousHeadOmitEmptyFloat32NPtr",
	"StructFieldAnonymousHeadStringTagFloat32NPtr",
	"StructFieldPtrHeadFloat32NPtr",
	"StructFieldPtrHeadOmitEmptyFloat32NPtr",
	"StructFieldPtrHeadStringTagFloat32NPtr",
	"StructFieldPtrAnonymousHeadFloat32NPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyFloat32NPtr",
	"StructFieldPtrAnonymousHeadStringTagFloat32NPtr",
	"StructFieldNPtrHeadFloat32NPtr",
	"StructFieldNPtrHeadOmitEmptyFloat32NPtr",
	"StructFieldNPtrHeadStringTagFloat32NPtr",
	"StructFieldNPtrAnonymousHeadFloat32NPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyFloat32NPtr",
	"StructFieldNPtrAnonymousHeadStringTagFloat32NPtr",
	"StructFieldHeadFloat64NPtr",
	"StructFieldHeadOmitEmptyFloat64NPtr",
	"StructFieldHeadStringTagFloat64NPtr",
	"StructFieldAnonymousHeadFloat64NPtr",
	"StructFieldAnonymousHeadOmitEmptyFloat64NPtr",
	"StructFieldAnonymousHeadStringTagFloat64NPtr",
	"StructFieldPtrHeadFloat64NPtr",
	"StructFieldPtrHeadOmitEmptyFloat64NPtr",
	"StructFieldPtrHeadStringTagFloat64NPtr",
	"StructFieldPtrAnonymousHeadFloat64NPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyFloat64NPtr",
	"StructFieldPtrAnonymousHeadStringTagFloat64NPtr",
	"StructFieldNPtrHeadFloat64NPtr",
	"StructFieldNPtrHeadOmitEmptyFloat64NPtr",
	"StructFieldNPtrHeadStringTagFloat64NPtr",
	"StructFieldNPtrAnonymousHeadFloat64NPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyFloat64NPtr",
	"StructFieldNPtrAnonymousHeadStringTagFloat64NPtr",
	"StructFieldHeadBoolNPtr",
	"StructFieldHeadOmitEmptyBoolNPtr",
	"StructFieldHeadStringTagBoolNPtr",
	"StructFieldAnonymousHeadBoolNPtr",
	"StructFieldAnonymousHeadOmitEmptyBoolNPtr",
	"StructFieldAnonymousHeadStringTagBoolNPtr",
	"StructFieldPtrHeadBoolNPtr",
	"StructFieldPtrHeadOmitEmptyBoolNPtr",
	"StructFieldPtrHeadStringTagBoolNPtr",
	"StructFieldPtrAnonymousHeadBoolNPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyBoolNPtr",
	"StructFieldPtrAnonymousHeadStringTagBoolNPtr",
	"StructFieldNPtrHeadBoolNPtr",
	"StructFieldNPtrHeadOmitEmptyBoolNPtr",
	"StructFieldNPtrHeadStringTagBoolNPtr",
	"StructFieldNPtrAnonymousHeadBoolNPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyBoolNPtr",
	"StructFieldNPtrAnonymousHeadStringTagBoolNPtr",
	"StructFieldHeadStringNPtr",
	"StructFieldHeadOmitEmptyStringNPtr",
	"StructFieldHeadStringTagStringNPtr",
	"StructFieldAnonymousHeadStringNPtr",
	"StructFieldAnonymousHeadOmitEmptyStringNPtr",
	"StructFieldAnonymousHeadStringTagStringNPtr",
	"StructFieldPtrHeadStringNPtr",
	"StructFieldPtrHeadOmitEmptyStringNPtr",
	"StructFieldPtrHeadStringTagStringNPtr",
	"StructFieldPtrAnonymousHeadStringNPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyStringNPtr",
	"StructFieldPtrAnonymousHeadStringTagStringNPtr",
	"StructFieldNPtrHeadStringNPtr",
	"StructFieldNPtrHeadOmitEmptyStringNPtr",
	"StructFieldNPtrHeadStringTagStringNPtr",
	"StructFieldNPtrAnonymousHeadStringNPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyStringNPtr",
	"StructFieldNPtrAnonymousHeadStringTagStringNPtr",
	"StructFieldHeadBytesNPtr",
	"StructFieldHeadOmitEmptyBytesNPtr",
	"StructFieldHeadStringTagBytesNPtr",
	"StructFieldAnonymousHeadBytesNPtr",
	"StructFieldAnonymousHeadOmitEmptyBytesNPtr",
	"StructFieldAnonymousHeadStringTagBytesNPtr",
	"StructFieldPtrHeadBytesNPtr",
	"StructFieldPtrHeadOmitEmptyBytesNPtr",
	"StructFieldPtrHeadStringTagBytesNPtr",
	"StructFieldPtrAnonymousHeadBytesNPtr",
	"StructFieldPtrAnonymousHeadOmitEmptyBytesNPtr",
	"StructFieldPtrAnonymousHeadStringTagBytesNPtr",
	"StructFieldNPtrHeadBytesNPtr",
	"StructFieldNPtrHeadOmitEmptyBytesNPtr",
	"StructFieldNPtrHeadStringTagBytesNPtr",
	"StructFieldNPtrAnonymousHeadBytesNPtr",
	"StructFieldNPtrAnonymousHeadOmitEmptyBytesNPtr",
	"StructFieldNPtrAnonymousHeadStringTagBytesNPtr",
	"StructFieldHead",
	"StructFieldHeadOmitEmpty",
	"StructFieldHeadStringTag",
	"StructFieldAnonymousHead",
	"StructFieldAnonymousHeadOmitEmpty",
	"StructFieldAnonymousHeadStringTag",
	"StructFieldPtrHead",
	"StructFieldPtrHeadOmitEmpty",
	"StructFieldPtrHeadStringTag",
	"StructFieldPtrAnonymousHead",
	"StructFieldPtrAnonymousHeadOmitEmpty",
	"StructFieldPtrAnonymousHeadStringTag",
	"StructFieldNPtrHead",
	"StructFieldNPtrHeadOmitEmpty",
	"StructFieldNPtrHeadStringTag",
	"StructFieldNPtrAnonymousHead",
	"StructFieldNPtrAnonymousHeadOmitEmpty",
	"StructFieldNPtrAnonymousHeadStringTag",
	"StructFieldInt",
	"StructFieldOmitEmptyInt",
	"StructFieldStringTagInt",
	"StructFieldUint",
	"StructFieldOmitEmptyUint",
	"StructFieldStringTagUint",
	"StructFieldFloat32",
	"StructFieldOmitEmptyFloat32",
	"StructFieldStringTagFloat32",
	"StructFieldFloat64",
	"StructFieldOmitEmptyFloat64",
	"StructFieldStringTagFloat64",
	"StructFieldBool",
	"StructFieldOmitEmptyBool",
	"StructFieldStringTagBool",
	"StructFieldString",
	"StructFieldOmitEmptyString",
	"StructFieldStringTagString",
	"StructFieldBytes",
	"StructFieldOmitEmptyBytes",
	"StructFieldStringTagBytes",
	"StructFieldArray",
	"StructFieldOmitEmptyArray",
	"StructFieldStringTagArray",
	"StructFieldMap",
	"StructFieldOmitEmptyMap",
	"StructFieldStringTagMap",
	"StructFieldMapLoad",
	"StructFieldOmitEmptyMapLoad",
	"StructFieldStringTagMapLoad",
	"StructFieldSlice",
	"StructFieldOmitEmptySlice",
	"StructFieldStringTagSlice",
	"StructFieldStruct",
	"StructFieldOmitEmptyStruct",
	"StructFieldStringTagStruct",
	"StructFieldMarshalJSON",
	"StructFieldOmitEmptyMarshalJSON",
	"StructFieldStringTagMarshalJSON",
	"StructFieldMarshalText",
	"StructFieldOmitEmptyMarshalText",
	"StructFieldStringTagMarshalText",
	"StructFieldRecursive",
	"StructFieldOmitEmptyRecursive",
	"StructFieldStringTagRecursive",
	"StructFieldIntString",
	"StructFieldOmitEmptyIntString",
	"StructFieldStringTagIntString",
	"StructFieldUintString",
	"StructFieldOmitEmptyUintString",
	"StructFieldStringTagUintString",
	"StructFieldIntPtr",
	"StructFieldOmitEmptyIntPtr",
	"StructFieldStringTagIntPtr",
	"StructFieldUintPtr",
	"StructFieldOmitEmptyUintPtr",
	"StructFieldStringTagUintPtr",
	"StructFieldFloat32Ptr",
	"StructFieldOmitEmptyFloat32Ptr",
	"StructFieldStringTagFloat32Ptr",
	"StructFieldFloat64Ptr",
	"StructFieldOmitEmptyFloat64Ptr",
	"StructFieldStringTagFloat64Ptr",
	"StructFieldBoolPtr",
	"StructFieldOmitEmptyBoolPtr",
	"StructFieldStringTagBoolPtr",
	"StructFieldStringPtr",
	"StructFieldOmitEmptyStringPtr",
	"StructFieldStringTagStringPtr",
	"StructFieldBytesPtr",
	"StructFieldOmitEmptyBytesPtr",
	"StructFieldStringTagBytesPtr",
	"StructFieldArrayPtr",
	"StructFieldOmitEmptyArrayPtr",
	"StructFieldStringTagArrayPtr",
	"StructFieldSlicePtr",
	"StructFieldOmitEmptySlicePtr",
	"StructFieldStringTagSlicePtr",
	"StructFieldMapPtr",
	"StructFieldOmitEmptyMapPtr",
	"StructFieldStringTagMapPtr",
	"StructFieldIntNPtr",
	"StructFieldOmitEmptyIntNPtr",
	"StructFieldStringTagIntNPtr",
	"StructFieldUintNPtr",
	"StructFieldOmitEmptyUintNPtr",
	"StructFieldStringTagUintNPtr",
	"StructFieldFloat32NPtr",
	"StructFieldOmitEmptyFloat32NPtr",
	"StructFieldStringTagFloat32NPtr",
	"StructFieldFloat64NPtr",
	"StructFieldOmitEmptyFloat64NPtr",
	"StructFieldStringTagFloat64NPtr",
	"StructFieldBoolNPtr",
	"StructFieldOmitEmptyBoolNPtr",
	"StructFieldStringTagBoolNPtr",
	"StructFieldStringNPtr",
	"StructFieldOmitEmptyStringNPtr",
	"StructFieldStringTagStringNPtr",
	"StructFieldBytesNPtr",
	"StructFieldOmitEmptyBytesNPtr",
	"StructFieldStringTagBytesNPtr",
	"StructField",
	"StructFieldOmitEmpty",
	"StructFieldStringTag",
	"StructEndInt",
	"StructEndOmitEmptyInt",
	"StructEndStringTagInt",
	"StructEndUint",
	"StructEndOmitEmptyUint",
	"StructEndStringTagUint",
	"StructEndFloat32",
	"StructEndOmitEmptyFloat32",
	"StructEndStringTagFloat32",
	"StructEndFloat64",
	"StructEndOmitEmptyFloat64",
	"StructEndStringTagFloat64",
	"StructEndBool",
	"StructEndOmitEmptyBool",
	"StructEndStringTagBool",
	"StructEndString",
	"StructEndOmitEmptyString",
	"StructEndStringTagString",
	"StructEndBytes",
	"StructEndOmitEmptyBytes",
	"StructEndStringTagBytes",
	"StructEndArray",
	"StructEndOmitEmptyArray",
	"StructEndStringTagArray",
	"StructEndMap",
	"StructEndOmitEmptyMap",
	"StructEndStringTagMap",
	"StructEndMapLoad",
	"StructEndOmitEmptyMapLoad",
	"StructEndStringTagMapLoad",
	"StructEndSlice",
	"StructEndOmitEmptySlice",
	"StructEndStringTagSlice",
	"StructEndStruct",
	"StructEndOmitEmptyStruct",
	"StructEndStringTagStruct",
	"StructEndMarshalJSON",
	"StructEndOmitEmptyMarshalJSON",
	"StructEndStringTagMarshalJSON",
	"StructEndMarshalText",
	"StructEndOmitEmptyMarshalText",
	"StructEndStringTagMarshalText",
	"StructEndRecursive",
	"StructEndOmitEmptyRecursive",
	"StructEndStringTagRecursive",
	"StructEndIntString",
	"StructEndOmitEmptyIntString",
	"StructEndStringTagIntString",
	"StructEndUintString",
	"StructEndOmitEmptyUintString",
	"StructEndStringTagUintString",
	"StructEndIntPtr",
	"StructEndOmitEmptyIntPtr",
	"StructEndStringTagIntPtr",
	"StructEndUintPtr",
	"StructEndOmitEmptyUintPtr",
	"StructEndStringTagUintPtr",
	"StructEndFloat32Ptr",
	"StructEndOmitEmptyFloat32Ptr",
	"StructEndStringTagFloat32Ptr",
	"StructEndFloat64Ptr",
	"StructEndOmitEmptyFloat64Ptr",
	"StructEndStringTagFloat64Ptr",
	"StructEndBoolPtr",
	"StructEndOmitEmptyBoolPtr",
	"StructEndStringTagBoolPtr",
	"StructEndStringPtr",
	"StructEndOmitEmptyStringPtr",
	"StructEndStringTagStringPtr",
	"StructEndBytesPtr",
	"StructEndOmitEmptyBytesPtr",
	"StructEndStringTagBytesPtr",
	"StructEndArrayPtr",
	"StructEndOmitEmptyArrayPtr",
	"StructEndStringTagArrayPtr",
	"StructEndSlicePtr",
	"StructEndOmitEmptySlicePtr",
	"StructEndStringTagSlicePtr",
	"StructEndMapPtr",
	"StructEndOmitEmptyMapPtr",
	"StructEndStringTagMapPtr",
	"StructEndIntNPtr",
	"StructEndOmitEmptyIntNPtr",
	"StructEndStringTagIntNPtr",
	"StructEndUintNPtr",
	"StructEndOmitEmptyUintNPtr",
	"StructEndStringTagUintNPtr",
	"StructEndFloat32NPtr",
	"StructEndOmitEmptyFloat32NPtr",
	"StructEndStringTagFloat32NPtr",
	"StructEndFloat64NPtr",
	"StructEndOmitEmptyFloat64NPtr",
	"StructEndStringTagFloat64NPtr",
	"StructEndBoolNPtr",
	"StructEndOmitEmptyBoolNPtr",
	"StructEndStringTagBoolNPtr",
	"StructEndStringNPtr",
	"StructEndOmitEmptyStringNPtr",
	"StructEndStringTagStringNPtr",
	"StructEndBytesNPtr",
	"StructEndOmitEmptyBytesNPtr",
	"StructEndStringTagBytesNPtr",
	"StructEnd",
	"StructEndOmitEmpty",
	"StructEndStringTag",
}

type opType int

const (
	opEnd                                              opType = 0
	opInterface                                        opType = 1
	opPtr                                              opType = 2
	opNPtr                                             opType = 3
	opSliceHead                                        opType = 4
	opRootSliceHead                                    opType = 5
	opSliceElem                                        opType = 6
	opRootSliceElem                                    opType = 7
	opSliceEnd                                         opType = 8
	opArrayHead                                        opType = 9
	opArrayElem                                        opType = 10
	opArrayEnd                                         opType = 11
	opMapHead                                          opType = 12
	opMapHeadLoad                                      opType = 13
	opMapKey                                           opType = 14
	opMapValue                                         opType = 15
	opMapEnd                                           opType = 16
	opStructFieldRecursiveEnd                          opType = 17
	opStructAnonymousEnd                               opType = 18
	opInt                                              opType = 19
	opUint                                             opType = 20
	opFloat32                                          opType = 21
	opFloat64                                          opType = 22
	opBool                                             opType = 23
	opString                                           opType = 24
	opBytes                                            opType = 25
	opArray                                            opType = 26
	opMap                                              opType = 27
	opMapLoad                                          opType = 28
	opSlice                                            opType = 29
	opStruct                                           opType = 30
	opMarshalJSON                                      opType = 31
	opMarshalText                                      opType = 32
	opRecursive                                        opType = 33
	opIntString                                        opType = 34
	opUintString                                       opType = 35
	opIntPtr                                           opType = 36
	opUintPtr                                          opType = 37
	opFloat32Ptr                                       opType = 38
	opFloat64Ptr                                       opType = 39
	opBoolPtr                                          opType = 40
	opStringPtr                                        opType = 41
	opBytesPtr                                         opType = 42
	opArrayPtr                                         opType = 43
	opSlicePtr                                         opType = 44
	opMapPtr                                           opType = 45
	opIntNPtr                                          opType = 46
	opUintNPtr                                         opType = 47
	opFloat32NPtr                                      opType = 48
	opFloat64NPtr                                      opType = 49
	opBoolNPtr                                         opType = 50
	opStringNPtr                                       opType = 51
	opBytesNPtr                                        opType = 52
	opStructFieldHeadInt                               opType = 53
	opStructFieldHeadOmitEmptyInt                      opType = 54
	opStructFieldHeadStringTagInt                      opType = 55
	opStructFieldAnonymousHeadInt                      opType = 56
	opStructFieldAnonymousHeadOmitEmptyInt             opType = 57
	opStructFieldAnonymousHeadStringTagInt             opType = 58
	opStructFieldPtrHeadInt                            opType = 59
	opStructFieldPtrHeadOmitEmptyInt                   opType = 60
	opStructFieldPtrHeadStringTagInt                   opType = 61
	opStructFieldPtrAnonymousHeadInt                   opType = 62
	opStructFieldPtrAnonymousHeadOmitEmptyInt          opType = 63
	opStructFieldPtrAnonymousHeadStringTagInt          opType = 64
	opStructFieldNPtrHeadInt                           opType = 65
	opStructFieldNPtrHeadOmitEmptyInt                  opType = 66
	opStructFieldNPtrHeadStringTagInt                  opType = 67
	opStructFieldNPtrAnonymousHeadInt                  opType = 68
	opStructFieldNPtrAnonymousHeadOmitEmptyInt         opType = 69
	opStructFieldNPtrAnonymousHeadStringTagInt         opType = 70
	opStructFieldHeadUint                              opType = 71
	opStructFieldHeadOmitEmptyUint                     opType = 72
	opStructFieldHeadStringTagUint                     opType = 73
	opStructFieldAnonymousHeadUint                     opType = 74
	opStructFieldAnonymousHeadOmitEmptyUint            opType = 75
	opStructFieldAnonymousHeadStringTagUint            opType = 76
	opStructFieldPtrHeadUint                           opType = 77
	opStructFieldPtrHeadOmitEmptyUint                  opType = 78
	opStructFieldPtrHeadStringTagUint                  opType = 79
	opStructFieldPtrAnonymousHeadUint                  opType = 80
	opStructFieldPtrAnonymousHeadOmitEmptyUint         opType = 81
	opStructFieldPtrAnonymousHeadStringTagUint         opType = 82
	opStructFieldNPtrHeadUint                          opType = 83
	opStructFieldNPtrHeadOmitEmptyUint                 opType = 84
	opStructFieldNPtrHeadStringTagUint                 opType = 85
	opStructFieldNPtrAnonymousHeadUint                 opType = 86
	opStructFieldNPtrAnonymousHeadOmitEmptyUint        opType = 87
	opStructFieldNPtrAnonymousHeadStringTagUint        opType = 88
	opStructFieldHeadFloat32                           opType = 89
	opStructFieldHeadOmitEmptyFloat32                  opType = 90
	opStructFieldHeadStringTagFloat32                  opType = 91
	opStructFieldAnonymousHeadFloat32                  opType = 92
	opStructFieldAnonymousHeadOmitEmptyFloat32         opType = 93
	opStructFieldAnonymousHeadStringTagFloat32         opType = 94
	opStructFieldPtrHeadFloat32                        opType = 95
	opStructFieldPtrHeadOmitEmptyFloat32               opType = 96
	opStructFieldPtrHeadStringTagFloat32               opType = 97
	opStructFieldPtrAnonymousHeadFloat32               opType = 98
	opStructFieldPtrAnonymousHeadOmitEmptyFloat32      opType = 99
	opStructFieldPtrAnonymousHeadStringTagFloat32      opType = 100
	opStructFieldNPtrHeadFloat32                       opType = 101
	opStructFieldNPtrHeadOmitEmptyFloat32              opType = 102
	opStructFieldNPtrHeadStringTagFloat32              opType = 103
	opStructFieldNPtrAnonymousHeadFloat32              opType = 104
	opStructFieldNPtrAnonymousHeadOmitEmptyFloat32     opType = 105
	opStructFieldNPtrAnonymousHeadStringTagFloat32     opType = 106
	opStructFieldHeadFloat64                           opType = 107
	opStructFieldHeadOmitEmptyFloat64                  opType = 108
	opStructFieldHeadStringTagFloat64                  opType = 109
	opStructFieldAnonymousHeadFloat64                  opType = 110
	opStructFieldAnonymousHeadOmitEmptyFloat64         opType = 111
	opStructFieldAnonymousHeadStringTagFloat64         opType = 112
	opStructFieldPtrHeadFloat64                        opType = 113
	opStructFieldPtrHeadOmitEmptyFloat64               opType = 114
	opStructFieldPtrHeadStringTagFloat64               opType = 115
	opStructFieldPtrAnonymousHeadFloat64               opType = 116
	opStructFieldPtrAnonymousHeadOmitEmptyFloat64      opType = 117
	opStructFieldPtrAnonymousHeadStringTagFloat64      opType = 118
	opStructFieldNPtrHeadFloat64                       opType = 119
	opStructFieldNPtrHeadOmitEmptyFloat64              opType = 120
	opStructFieldNPtrHeadStringTagFloat64              opType = 121
	opStructFieldNPtrAnonymousHeadFloat64              opType = 122
	opStructFieldNPtrAnonymousHeadOmitEmptyFloat64     opType = 123
	opStructFieldNPtrAnonymousHeadStringTagFloat64     opType = 124
	opStructFieldHeadBool                              opType = 125
	opStructFieldHeadOmitEmptyBool                     opType = 126
	opStructFieldHeadStringTagBool                     opType = 127
	opStructFieldAnonymousHeadBool                     opType = 128
	opStructFieldAnonymousHeadOmitEmptyBool            opType = 129
	opStructFieldAnonymousHeadStringTagBool            opType = 130
	opStructFieldPtrHeadBool                           opType = 131
	opStructFieldPtrHeadOmitEmptyBool                  opType = 132
	opStructFieldPtrHeadStringTagBool                  opType = 133
	opStructFieldPtrAnonymousHeadBool                  opType = 134
	opStructFieldPtrAnonymousHeadOmitEmptyBool         opType = 135
	opStructFieldPtrAnonymousHeadStringTagBool         opType = 136
	opStructFieldNPtrHeadBool                          opType = 137
	opStructFieldNPtrHeadOmitEmptyBool                 opType = 138
	opStructFieldNPtrHeadStringTagBool                 opType = 139
	opStructFieldNPtrAnonymousHeadBool                 opType = 140
	opStructFieldNPtrAnonymousHeadOmitEmptyBool        opType = 141
	opStructFieldNPtrAnonymousHeadStringTagBool        opType = 142
	opStructFieldHeadString                            opType = 143
	opStructFieldHeadOmitEmptyString                   opType = 144
	opStructFieldHeadStringTagString                   opType = 145
	opStructFieldAnonymousHeadString                   opType = 146
	opStructFieldAnonymousHeadOmitEmptyString          opType = 147
	opStructFieldAnonymousHeadStringTagString          opType = 148
	opStructFieldPtrHeadString                         opType = 149
	opStructFieldPtrHeadOmitEmptyString                opType = 150
	opStructFieldPtrHeadStringTagString                opType = 151
	opStructFieldPtrAnonymousHeadString                opType = 152
	opStructFieldPtrAnonymousHeadOmitEmptyString       opType = 153
	opStructFieldPtrAnonymousHeadStringTagString       opType = 154
	opStructFieldNPtrHeadString                        opType = 155
	opStructFieldNPtrHeadOmitEmptyString               opType = 156
	opStructFieldNPtrHeadStringTagString               opType = 157
	opStructFieldNPtrAnonymousHeadString               opType = 158
	opStructFieldNPtrAnonymousHeadOmitEmptyString      opType = 159
	opStructFieldNPtrAnonymousHeadStringTagString      opType = 160
	opStructFieldHeadBytes                             opType = 161
	opStructFieldHeadOmitEmptyBytes                    opType = 162
	opStructFieldHeadStringTagBytes                    opType = 163
	opStructFieldAnonymousHeadBytes                    opType = 164
	opStructFieldAnonymousHeadOmitEmptyBytes           opType = 165
	opStructFieldAnonymousHeadStringTagBytes           opType = 166
	opStructFieldPtrHeadBytes                          opType = 167
	opStructFieldPtrHeadOmitEmptyBytes                 opType = 168
	opStructFieldPtrHeadStringTagBytes                 opType = 169
	opStructFieldPtrAnonymousHeadBytes                 opType = 170
	opStructFieldPtrAnonymousHeadOmitEmptyBytes        opType = 171
	opStructFieldPtrAnonymousHeadStringTagBytes        opType = 172
	opStructFieldNPtrHeadBytes                         opType = 173
	opStructFieldNPtrHeadOmitEmptyBytes                opType = 174
	opStructFieldNPtrHeadStringTagBytes                opType = 175
	opStructFieldNPtrAnonymousHeadBytes                opType = 176
	opStructFieldNPtrAnonymousHeadOmitEmptyBytes       opType = 177
	opStructFieldNPtrAnonymousHeadStringTagBytes       opType = 178
	opStructFieldHeadArray                             opType = 179
	opStructFieldHeadOmitEmptyArray                    opType = 180
	opStructFieldHeadStringTagArray                    opType = 181
	opStructFieldAnonymousHeadArray                    opType = 182
	opStructFieldAnonymousHeadOmitEmptyArray           opType = 183
	opStructFieldAnonymousHeadStringTagArray           opType = 184
	opStructFieldPtrHeadArray                          opType = 185
	opStructFieldPtrHeadOmitEmptyArray                 opType = 186
	opStructFieldPtrHeadStringTagArray                 opType = 187
	opStructFieldPtrAnonymousHeadArray                 opType = 188
	opStructFieldPtrAnonymousHeadOmitEmptyArray        opType = 189
	opStructFieldPtrAnonymousHeadStringTagArray        opType = 190
	opStructFieldNPtrHeadArray                         opType = 191
	opStructFieldNPtrHeadOmitEmptyArray                opType = 192
	opStructFieldNPtrHeadStringTagArray                opType = 193
	opStructFieldNPtrAnonymousHeadArray                opType = 194
	opStructFieldNPtrAnonymousHeadOmitEmptyArray       opType = 195
	opStructFieldNPtrAnonymousHeadStringTagArray       opType = 196
	opStructFieldHeadMap                               opType = 197
	opStructFieldHeadOmitEmptyMap                      opType = 198
	opStructFieldHeadStringTagMap                      opType = 199
	opStructFieldAnonymousHeadMap                      opType = 200
	opStructFieldAnonymousHeadOmitEmptyMap             opType = 201
	opStructFieldAnonymousHeadStringTagMap             opType = 202
	opStructFieldPtrHeadMap                            opType = 203
	opStructFieldPtrHeadOmitEmptyMap                   opType = 204
	opStructFieldPtrHeadStringTagMap                   opType = 205
	opStructFieldPtrAnonymousHeadMap                   opType = 206
	opStructFieldPtrAnonymousHeadOmitEmptyMap          opType = 207
	opStructFieldPtrAnonymousHeadStringTagMap          opType = 208
	opStructFieldNPtrHeadMap                           opType = 209
	opStructFieldNPtrHeadOmitEmptyMap                  opType = 210
	opStructFieldNPtrHeadStringTagMap                  opType = 211
	opStructFieldNPtrAnonymousHeadMap                  opType = 212
	opStructFieldNPtrAnonymousHeadOmitEmptyMap         opType = 213
	opStructFieldNPtrAnonymousHeadStringTagMap         opType = 214
	opStructFieldHeadMapLoad                           opType = 215
	opStructFieldHeadOmitEmptyMapLoad                  opType = 216
	opStructFieldHeadStringTagMapLoad                  opType = 217
	opStructFieldAnonymousHeadMapLoad                  opType = 218
	opStructFieldAnonymousHeadOmitEmptyMapLoad         opType = 219
	opStructFieldAnonymousHeadStringTagMapLoad         opType = 220
	opStructFieldPtrHeadMapLoad                        opType = 221
	opStructFieldPtrHeadOmitEmptyMapLoad               opType = 222
	opStructFieldPtrHeadStringTagMapLoad               opType = 223
	opStructFieldPtrAnonymousHeadMapLoad               opType = 224
	opStructFieldPtrAnonymousHeadOmitEmptyMapLoad      opType = 225
	opStructFieldPtrAnonymousHeadStringTagMapLoad      opType = 226
	opStructFieldNPtrHeadMapLoad                       opType = 227
	opStructFieldNPtrHeadOmitEmptyMapLoad              opType = 228
	opStructFieldNPtrHeadStringTagMapLoad              opType = 229
	opStructFieldNPtrAnonymousHeadMapLoad              opType = 230
	opStructFieldNPtrAnonymousHeadOmitEmptyMapLoad     opType = 231
	opStructFieldNPtrAnonymousHeadStringTagMapLoad     opType = 232
	opStructFieldHeadSlice                             opType = 233
	opStructFieldHeadOmitEmptySlice                    opType = 234
	opStructFieldHeadStringTagSlice                    opType = 235
	opStructFieldAnonymousHeadSlice                    opType = 236
	opStructFieldAnonymousHeadOmitEmptySlice           opType = 237
	opStructFieldAnonymousHeadStringTagSlice           opType = 238
	opStructFieldPtrHeadSlice                          opType = 239
	opStructFieldPtrHeadOmitEmptySlice                 opType = 240
	opStructFieldPtrHeadStringTagSlice                 opType = 241
	opStructFieldPtrAnonymousHeadSlice                 opType = 242
	opStructFieldPtrAnonymousHeadOmitEmptySlice        opType = 243
	opStructFieldPtrAnonymousHeadStringTagSlice        opType = 244
	opStructFieldNPtrHeadSlice                         opType = 245
	opStructFieldNPtrHeadOmitEmptySlice                opType = 246
	opStructFieldNPtrHeadStringTagSlice                opType = 247
	opStructFieldNPtrAnonymousHeadSlice                opType = 248
	opStructFieldNPtrAnonymousHeadOmitEmptySlice       opType = 249
	opStructFieldNPtrAnonymousHeadStringTagSlice       opType = 250
	opStructFieldHeadStruct                            opType = 251
	opStructFieldHeadOmitEmptyStruct                   opType = 252
	opStructFieldHeadStringTagStruct                   opType = 253
	opStructFieldAnonymousHeadStruct                   opType = 254
	opStructFieldAnonymousHeadOmitEmptyStruct          opType = 255
	opStructFieldAnonymousHeadStringTagStruct          opType = 256
	opStructFieldPtrHeadStruct                         opType = 257
	opStructFieldPtrHeadOmitEmptyStruct                opType = 258
	opStructFieldPtrHeadStringTagStruct                opType = 259
	opStructFieldPtrAnonymousHeadStruct                opType = 260
	opStructFieldPtrAnonymousHeadOmitEmptyStruct       opType = 261
	opStructFieldPtrAnonymousHeadStringTagStruct       opType = 262
	opStructFieldNPtrHeadStruct                        opType = 263
	opStructFieldNPtrHeadOmitEmptyStruct               opType = 264
	opStructFieldNPtrHeadStringTagStruct               opType = 265
	opStructFieldNPtrAnonymousHeadStruct               opType = 266
	opStructFieldNPtrAnonymousHeadOmitEmptyStruct      opType = 267
	opStructFieldNPtrAnonymousHeadStringTagStruct      opType = 268
	opStructFieldHeadMarshalJSON                       opType = 269
	opStructFieldHeadOmitEmptyMarshalJSON              opType = 270
	opStructFieldHeadStringTagMarshalJSON              opType = 271
	opStructFieldAnonymousHeadMarshalJSON              opType = 272
	opStructFieldAnonymousHeadOmitEmptyMarshalJSON     opType = 273
	opStructFieldAnonymousHeadStringTagMarshalJSON     opType = 274
	opStructFieldPtrHeadMarshalJSON                    opType = 275
	opStructFieldPtrHeadOmitEmptyMarshalJSON           opType = 276
	opStructFieldPtrHeadStringTagMarshalJSON           opType = 277
	opStructFieldPtrAnonymousHeadMarshalJSON           opType = 278
	opStructFieldPtrAnonymousHeadOmitEmptyMarshalJSON  opType = 279
	opStructFieldPtrAnonymousHeadStringTagMarshalJSON  opType = 280
	opStructFieldNPtrHeadMarshalJSON                   opType = 281
	opStructFieldNPtrHeadOmitEmptyMarshalJSON          opType = 282
	opStructFieldNPtrHeadStringTagMarshalJSON          opType = 283
	opStructFieldNPtrAnonymousHeadMarshalJSON          opType = 284
	opStructFieldNPtrAnonymousHeadOmitEmptyMarshalJSON opType = 285
	opStructFieldNPtrAnonymousHeadStringTagMarshalJSON opType = 286
	opStructFieldHeadMarshalText                       opType = 287
	opStructFieldHeadOmitEmptyMarshalText              opType = 288
	opStructFieldHeadStringTagMarshalText              opType = 289
	opStructFieldAnonymousHeadMarshalText              opType = 290
	opStructFieldAnonymousHeadOmitEmptyMarshalText     opType = 291
	opStructFieldAnonymousHeadStringTagMarshalText     opType = 292
	opStructFieldPtrHeadMarshalText                    opType = 293
	opStructFieldPtrHeadOmitEmptyMarshalText           opType = 294
	opStructFieldPtrHeadStringTagMarshalText           opType = 295
	opStructFieldPtrAnonymousHeadMarshalText           opType = 296
	opStructFieldPtrAnonymousHeadOmitEmptyMarshalText  opType = 297
	opStructFieldPtrAnonymousHeadStringTagMarshalText  opType = 298
	opStructFieldNPtrHeadMarshalText                   opType = 299
	opStructFieldNPtrHeadOmitEmptyMarshalText          opType = 300
	opStructFieldNPtrHeadStringTagMarshalText          opType = 301
	opStructFieldNPtrAnonymousHeadMarshalText          opType = 302
	opStructFieldNPtrAnonymousHeadOmitEmptyMarshalText opType = 303
	opStructFieldNPtrAnonymousHeadStringTagMarshalText opType = 304
	opStructFieldHeadRecursive                         opType = 305
	opStructFieldHeadOmitEmptyRecursive                opType = 306
	opStructFieldHeadStringTagRecursive                opType = 307
	opStructFieldAnonymousHeadRecursive                opType = 308
	opStructFieldAnonymousHeadOmitEmptyRecursive       opType = 309
	opStructFieldAnonymousHeadStringTagRecursive       opType = 310
	opStructFieldPtrHeadRecursive                      opType = 311
	opStructFieldPtrHeadOmitEmptyRecursive             opType = 312
	opStructFieldPtrHeadStringTagRecursive             opType = 313
	opStructFieldPtrAnonymousHeadRecursive             opType = 314
	opStructFieldPtrAnonymousHeadOmitEmptyRecursive    opType = 315
	opStructFieldPtrAnonymousHeadStringTagRecursive    opType = 316
	opStructFieldNPtrHeadRecursive                     opType = 317
	opStructFieldNPtrHeadOmitEmptyRecursive            opType = 318
	opStructFieldNPtrHeadStringTagRecursive            opType = 319
	opStructFieldNPtrAnonymousHeadRecursive            opType = 320
	opStructFieldNPtrAnonymousHeadOmitEmptyRecursive   opType = 321
	opStructFieldNPtrAnonymousHeadStringTagRecursive   opType = 322
	opStructFieldHeadIntString                         opType = 323
	opStructFieldHeadOmitEmptyIntString                opType = 324
	opStructFieldHeadStringTagIntString                opType = 325
	opStructFieldAnonymousHeadIntString                opType = 326
	opStructFieldAnonymousHeadOmitEmptyIntString       opType = 327
	opStructFieldAnonymousHeadStringTagIntString       opType = 328
	opStructFieldPtrHeadIntString                      opType = 329
	opStructFieldPtrHeadOmitEmptyIntString             opType = 330
	opStructFieldPtrHeadStringTagIntString             opType = 331
	opStructFieldPtrAnonymousHeadIntString             opType = 332
	opStructFieldPtrAnonymousHeadOmitEmptyIntString    opType = 333
	opStructFieldPtrAnonymousHeadStringTagIntString    opType = 334
	opStructFieldNPtrHeadIntString                     opType = 335
	opStructFieldNPtrHeadOmitEmptyIntString            opType = 336
	opStructFieldNPtrHeadStringTagIntString            opType = 337
	opStructFieldNPtrAnonymousHeadIntString            opType = 338
	opStructFieldNPtrAnonymousHeadOmitEmptyIntString   opType = 339
	opStructFieldNPtrAnonymousHeadStringTagIntString   opType = 340
	opStructFieldHeadUintString                        opType = 341
	opStructFieldHeadOmitEmptyUintString               opType = 342
	opStructFieldHeadStringTagUintString               opType = 343
	opStructFieldAnonymousHeadUintString               opType = 344
	opStructFieldAnonymousHeadOmitEmptyUintString      opType = 345
	opStructFieldAnonymousHeadStringTagUintString      opType = 346
	opStructFieldPtrHeadUintString                     opType = 347
	opStructFieldPtrHeadOmitEmptyUintString            opType = 348
	opStructFieldPtrHeadStringTagUintString            opType = 349
	opStructFieldPtrAnonymousHeadUintString            opType = 350
	opStructFieldPtrAnonymousHeadOmitEmptyUintString   opType = 351
	opStructFieldPtrAnonymousHeadStringTagUintString   opType = 352
	opStructFieldNPtrHeadUintString                    opType = 353
	opStructFieldNPtrHeadOmitEmptyUintString           opType = 354
	opStructFieldNPtrHeadStringTagUintString           opType = 355
	opStructFieldNPtrAnonymousHeadUintString           opType = 356
	opStructFieldNPtrAnonymousHeadOmitEmptyUintString  opType = 357
	opStructFieldNPtrAnonymousHeadStringTagUintString  opType = 358
	opStructFieldHeadIntPtr                            opType = 359
	opStructFieldHeadOmitEmptyIntPtr                   opType = 360
	opStructFieldHeadStringTagIntPtr                   opType = 361
	opStructFieldAnonymousHeadIntPtr                   opType = 362
	opStructFieldAnonymousHeadOmitEmptyIntPtr          opType = 363
	opStructFieldAnonymousHeadStringTagIntPtr          opType = 364
	opStructFieldPtrHeadIntPtr                         opType = 365
	opStructFieldPtrHeadOmitEmptyIntPtr                opType = 366
	opStructFieldPtrHeadStringTagIntPtr                opType = 367
	opStructFieldPtrAnonymousHeadIntPtr                opType = 368
	opStructFieldPtrAnonymousHeadOmitEmptyIntPtr       opType = 369
	opStructFieldPtrAnonymousHeadStringTagIntPtr       opType = 370
	opStructFieldNPtrHeadIntPtr                        opType = 371
	opStructFieldNPtrHeadOmitEmptyIntPtr               opType = 372
	opStructFieldNPtrHeadStringTagIntPtr               opType = 373
	opStructFieldNPtrAnonymousHeadIntPtr               opType = 374
	opStructFieldNPtrAnonymousHeadOmitEmptyIntPtr      opType = 375
	opStructFieldNPtrAnonymousHeadStringTagIntPtr      opType = 376
	opStructFieldHeadUintPtr                           opType = 377
	opStructFieldHeadOmitEmptyUintPtr                  opType = 378
	opStructFieldHeadStringTagUintPtr                  opType = 379
	opStructFieldAnonymousHeadUintPtr                  opType = 380
	opStructFieldAnonymousHeadOmitEmptyUintPtr         opType = 381
	opStructFieldAnonymousHeadStringTagUintPtr         opType = 382
	opStructFieldPtrHeadUintPtr                        opType = 383
	opStructFieldPtrHeadOmitEmptyUintPtr               opType = 384
	opStructFieldPtrHeadStringTagUintPtr               opType = 385
	opStructFieldPtrAnonymousHeadUintPtr               opType = 386
	opStructFieldPtrAnonymousHeadOmitEmptyUintPtr      opType = 387
	opStructFieldPtrAnonymousHeadStringTagUintPtr      opType = 388
	opStructFieldNPtrHeadUintPtr                       opType = 389
	opStructFieldNPtrHeadOmitEmptyUintPtr              opType = 390
	opStructFieldNPtrHeadStringTagUintPtr              opType = 391
	opStructFieldNPtrAnonymousHeadUintPtr              opType = 392
	opStructFieldNPtrAnonymousHeadOmitEmptyUintPtr     opType = 393
	opStructFieldNPtrAnonymousHeadStringTagUintPtr     opType = 394
	opStructFieldHeadFloat32Ptr                        opType = 395
	opStructFieldHeadOmitEmptyFloat32Ptr               opType = 396
	opStructFieldHeadStringTagFloat32Ptr               opType = 397
	opStructFieldAnonymousHeadFloat32Ptr               opType = 398
	opStructFieldAnonymousHeadOmitEmptyFloat32Ptr      opType = 399
	opStructFieldAnonymousHeadStringTagFloat32Ptr      opType = 400
	opStructFieldPtrHeadFloat32Ptr                     opType = 401
	opStructFieldPtrHeadOmitEmptyFloat32Ptr            opType = 402
	opStructFieldPtrHeadStringTagFloat32Ptr            opType = 403
	opStructFieldPtrAnonymousHeadFloat32Ptr            opType = 404
	opStructFieldPtrAnonymousHeadOmitEmptyFloat32Ptr   opType = 405
	opStructFieldPtrAnonymousHeadStringTagFloat32Ptr   opType = 406
	opStructFieldNPtrHeadFloat32Ptr                    opType = 407
	opStructFieldNPtrHeadOmitEmptyFloat32Ptr           opType = 408
	opStructFieldNPtrHeadStringTagFloat32Ptr           opType = 409
	opStructFieldNPtrAnonymousHeadFloat32Ptr           opType = 410
	opStructFieldNPtrAnonymousHeadOmitEmptyFloat32Ptr  opType = 411
	opStructFieldNPtrAnonymousHeadStringTagFloat32Ptr  opType = 412
	opStructFieldHeadFloat64Ptr                        opType = 413
	opStructFieldHeadOmitEmptyFloat64Ptr               opType = 414
	opStructFieldHeadStringTagFloat64Ptr               opType = 415
	opStructFieldAnonymousHeadFloat64Ptr               opType = 416
	opStructFieldAnonymousHeadOmitEmptyFloat64Ptr      opType = 417
	opStructFieldAnonymousHeadStringTagFloat64Ptr      opType = 418
	opStructFieldPtrHeadFloat64Ptr                     opType = 419
	opStructFieldPtrHeadOmitEmptyFloat64Ptr            opType = 420
	opStructFieldPtrHeadStringTagFloat64Ptr            opType = 421
	opStructFieldPtrAnonymousHeadFloat64Ptr            opType = 422
	opStructFieldPtrAnonymousHeadOmitEmptyFloat64Ptr   opType = 423
	opStructFieldPtrAnonymousHeadStringTagFloat64Ptr   opType = 424
	opStructFieldNPtrHeadFloat64Ptr                    opType = 425
	opStructFieldNPtrHeadOmitEmptyFloat64Ptr           opType = 426
	opStructFieldNPtrHeadStringTagFloat64Ptr           opType = 427
	opStructFieldNPtrAnonymousHeadFloat64Ptr           opType = 428
	opStructFieldNPtrAnonymousHeadOmitEmptyFloat64Ptr  opType = 429
	opStructFieldNPtrAnonymousHeadStringTagFloat64Ptr  opType = 430
	opStructFieldHeadBoolPtr                           opType = 431
	opStructFieldHeadOmitEmptyBoolPtr                  opType = 432
	opStructFieldHeadStringTagBoolPtr                  opType = 433
	opStructFieldAnonymousHeadBoolPtr                  opType = 434
	opStructFieldAnonymousHeadOmitEmptyBoolPtr         opType = 435
	opStructFieldAnonymousHeadStringTagBoolPtr         opType = 436
	opStructFieldPtrHeadBoolPtr                        opType = 437
	opStructFieldPtrHeadOmitEmptyBoolPtr               opType = 438
	opStructFieldPtrHeadStringTagBoolPtr               opType = 439
	opStructFieldPtrAnonymousHeadBoolPtr               opType = 440
	opStructFieldPtrAnonymousHeadOmitEmptyBoolPtr      opType = 441
	opStructFieldPtrAnonymousHeadStringTagBoolPtr      opType = 442
	opStructFieldNPtrHeadBoolPtr                       opType = 443
	opStructFieldNPtrHeadOmitEmptyBoolPtr              opType = 444
	opStructFieldNPtrHeadStringTagBoolPtr              opType = 445
	opStructFieldNPtrAnonymousHeadBoolPtr              opType = 446
	opStructFieldNPtrAnonymousHeadOmitEmptyBoolPtr     opType = 447
	opStructFieldNPtrAnonymousHeadStringTagBoolPtr     opType = 448
	opStructFieldHeadStringPtr                         opType = 449
	opStructFieldHeadOmitEmptyStringPtr                opType = 450
	opStructFieldHeadStringTagStringPtr                opType = 451
	opStructFieldAnonymousHeadStringPtr                opType = 452
	opStructFieldAnonymousHeadOmitEmptyStringPtr       opType = 453
	opStructFieldAnonymousHeadStringTagStringPtr       opType = 454
	opStructFieldPtrHeadStringPtr                      opType = 455
	opStructFieldPtrHeadOmitEmptyStringPtr             opType = 456
	opStructFieldPtrHeadStringTagStringPtr             opType = 457
	opStructFieldPtrAnonymousHeadStringPtr             opType = 458
	opStructFieldPtrAnonymousHeadOmitEmptyStringPtr    opType = 459
	opStructFieldPtrAnonymousHeadStringTagStringPtr    opType = 460
	opStructFieldNPtrHeadStringPtr                     opType = 461
	opStructFieldNPtrHeadOmitEmptyStringPtr            opType = 462
	opStructFieldNPtrHeadStringTagStringPtr            opType = 463
	opStructFieldNPtrAnonymousHeadStringPtr            opType = 464
	opStructFieldNPtrAnonymousHeadOmitEmptyStringPtr   opType = 465
	opStructFieldNPtrAnonymousHeadStringTagStringPtr   opType = 466
	opStructFieldHeadBytesPtr                          opType = 467
	opStructFieldHeadOmitEmptyBytesPtr                 opType = 468
	opStructFieldHeadStringTagBytesPtr                 opType = 469
	opStructFieldAnonymousHeadBytesPtr                 opType = 470
	opStructFieldAnonymousHeadOmitEmptyBytesPtr        opType = 471
	opStructFieldAnonymousHeadStringTagBytesPtr        opType = 472
	opStructFieldPtrHeadBytesPtr                       opType = 473
	opStructFieldPtrHeadOmitEmptyBytesPtr              opType = 474
	opStructFieldPtrHeadStringTagBytesPtr              opType = 475
	opStructFieldPtrAnonymousHeadBytesPtr              opType = 476
	opStructFieldPtrAnonymousHeadOmitEmptyBytesPtr     opType = 477
	opStructFieldPtrAnonymousHeadStringTagBytesPtr     opType = 478
	opStructFieldNPtrHeadBytesPtr                      opType = 479
	opStructFieldNPtrHeadOmitEmptyBytesPtr             opType = 480
	opStructFieldNPtrHeadStringTagBytesPtr             opType = 481
	opStructFieldNPtrAnonymousHeadBytesPtr             opType = 482
	opStructFieldNPtrAnonymousHeadOmitEmptyBytesPtr    opType = 483
	opStructFieldNPtrAnonymousHeadStringTagBytesPtr    opType = 484
	opStructFieldHeadArrayPtr                          opType = 485
	opStructFieldHeadOmitEmptyArrayPtr                 opType = 486
	opStructFieldHeadStringTagArrayPtr                 opType = 487
	opStructFieldAnonymousHeadArrayPtr                 opType = 488
	opStructFieldAnonymousHeadOmitEmptyArrayPtr        opType = 489
	opStructFieldAnonymousHeadStringTagArrayPtr        opType = 490
	opStructFieldPtrHeadArrayPtr                       opType = 491
	opStructFieldPtrHeadOmitEmptyArrayPtr              opType = 492
	opStructFieldPtrHeadStringTagArrayPtr              opType = 493
	opStructFieldPtrAnonymousHeadArrayPtr              opType = 494
	opStructFieldPtrAnonymousHeadOmitEmptyArrayPtr     opType = 495
	opStructFieldPtrAnonymousHeadStringTagArrayPtr     opType = 496
	opStructFieldNPtrHeadArrayPtr                      opType = 497
	opStructFieldNPtrHeadOmitEmptyArrayPtr             opType = 498
	opStructFieldNPtrHeadStringTagArrayPtr             opType = 499
	opStructFieldNPtrAnonymousHeadArrayPtr             opType = 500
	opStructFieldNPtrAnonymousHeadOmitEmptyArrayPtr    opType = 501
	opStructFieldNPtrAnonymousHeadStringTagArrayPtr    opType = 502
	opStructFieldHeadSlicePtr                          opType = 503
	opStructFieldHeadOmitEmptySlicePtr                 opType = 504
	opStructFieldHeadStringTagSlicePtr                 opType = 505
	opStructFieldAnonymousHeadSlicePtr                 opType = 506
	opStructFieldAnonymousHeadOmitEmptySlicePtr        opType = 507
	opStructFieldAnonymousHeadStringTagSlicePtr        opType = 508
	opStructFieldPtrHeadSlicePtr                       opType = 509
	opStructFieldPtrHeadOmitEmptySlicePtr              opType = 510
	opStructFieldPtrHeadStringTagSlicePtr              opType = 511
	opStructFieldPtrAnonymousHeadSlicePtr              opType = 512
	opStructFieldPtrAnonymousHeadOmitEmptySlicePtr     opType = 513
	opStructFieldPtrAnonymousHeadStringTagSlicePtr     opType = 514
	opStructFieldNPtrHeadSlicePtr                      opType = 515
	opStructFieldNPtrHeadOmitEmptySlicePtr             opType = 516
	opStructFieldNPtrHeadStringTagSlicePtr             opType = 517
	opStructFieldNPtrAnonymousHeadSlicePtr             opType = 518
	opStructFieldNPtrAnonymousHeadOmitEmptySlicePtr    opType = 519
	opStructFieldNPtrAnonymousHeadStringTagSlicePtr    opType = 520
	opStructFieldHeadMapPtr                            opType = 521
	opStructFieldHeadOmitEmptyMapPtr                   opType = 522
	opStructFieldHeadStringTagMapPtr                   opType = 523
	opStructFieldAnonymousHeadMapPtr                   opType = 524
	opStructFieldAnonymousHeadOmitEmptyMapPtr          opType = 525
	opStructFieldAnonymousHeadStringTagMapPtr          opType = 526
	opStructFieldPtrHeadMapPtr                         opType = 527
	opStructFieldPtrHeadOmitEmptyMapPtr                opType = 528
	opStructFieldPtrHeadStringTagMapPtr                opType = 529
	opStructFieldPtrAnonymousHeadMapPtr                opType = 530
	opStructFieldPtrAnonymousHeadOmitEmptyMapPtr       opType = 531
	opStructFieldPtrAnonymousHeadStringTagMapPtr       opType = 532
	opStructFieldNPtrHeadMapPtr                        opType = 533
	opStructFieldNPtrHeadOmitEmptyMapPtr               opType = 534
	opStructFieldNPtrHeadStringTagMapPtr               opType = 535
	opStructFieldNPtrAnonymousHeadMapPtr               opType = 536
	opStructFieldNPtrAnonymousHeadOmitEmptyMapPtr      opType = 537
	opStructFieldNPtrAnonymousHeadStringTagMapPtr      opType = 538
	opStructFieldHeadIntNPtr                           opType = 539
	opStructFieldHeadOmitEmptyIntNPtr                  opType = 540
	opStructFieldHeadStringTagIntNPtr                  opType = 541
	opStructFieldAnonymousHeadIntNPtr                  opType = 542
	opStructFieldAnonymousHeadOmitEmptyIntNPtr         opType = 543
	opStructFieldAnonymousHeadStringTagIntNPtr         opType = 544
	opStructFieldPtrHeadIntNPtr                        opType = 545
	opStructFieldPtrHeadOmitEmptyIntNPtr               opType = 546
	opStructFieldPtrHeadStringTagIntNPtr               opType = 547
	opStructFieldPtrAnonymousHeadIntNPtr               opType = 548
	opStructFieldPtrAnonymousHeadOmitEmptyIntNPtr      opType = 549
	opStructFieldPtrAnonymousHeadStringTagIntNPtr      opType = 550
	opStructFieldNPtrHeadIntNPtr                       opType = 551
	opStructFieldNPtrHeadOmitEmptyIntNPtr              opType = 552
	opStructFieldNPtrHeadStringTagIntNPtr              opType = 553
	opStructFieldNPtrAnonymousHeadIntNPtr              opType = 554
	opStructFieldNPtrAnonymousHeadOmitEmptyIntNPtr     opType = 555
	opStructFieldNPtrAnonymousHeadStringTagIntNPtr     opType = 556
	opStructFieldHeadUintNPtr                          opType = 557
	opStructFieldHeadOmitEmptyUintNPtr                 opType = 558
	opStructFieldHeadStringTagUintNPtr                 opType = 559
	opStructFieldAnonymousHeadUintNPtr                 opType = 560
	opStructFieldAnonymousHeadOmitEmptyUintNPtr        opType = 561
	opStructFieldAnonymousHeadStringTagUintNPtr        opType = 562
	opStructFieldPtrHeadUintNPtr                       opType = 563
	opStructFieldPtrHeadOmitEmptyUintNPtr              opType = 564
	opStructFieldPtrHeadStringTagUintNPtr              opType = 565
	opStructFieldPtrAnonymousHeadUintNPtr              opType = 566
	opStructFieldPtrAnonymousHeadOmitEmptyUintNPtr     opType = 567
	opStructFieldPtrAnonymousHeadStringTagUintNPtr     opType = 568
	opStructFieldNPtrHeadUintNPtr                      opType = 569
	opStructFieldNPtrHeadOmitEmptyUintNPtr             opType = 570
	opStructFieldNPtrHeadStringTagUintNPtr             opType = 571
	opStructFieldNPtrAnonymousHeadUintNPtr             opType = 572
	opStructFieldNPtrAnonymousHeadOmitEmptyUintNPtr    opType = 573
	opStructFieldNPtrAnonymousHeadStringTagUintNPtr    opType = 574
	opStructFieldHeadFloat32NPtr                       opType = 575
	opStructFieldHeadOmitEmptyFloat32NPtr              opType = 576
	opStructFieldHeadStringTagFloat32NPtr              opType = 577
	opStructFieldAnonymousHeadFloat32NPtr              opType = 578
	opStructFieldAnonymousHeadOmitEmptyFloat32NPtr     opType = 579
	opStructFieldAnonymousHeadStringTagFloat32NPtr     opType = 580
	opStructFieldPtrHeadFloat32NPtr                    opType = 581
	opStructFieldPtrHeadOmitEmptyFloat32NPtr           opType = 582
	opStructFieldPtrHeadStringTagFloat32NPtr           opType = 583
	opStructFieldPtrAnonymousHeadFloat32NPtr           opType = 584
	opStructFieldPtrAnonymousHeadOmitEmptyFloat32NPtr  opType = 585
	opStructFieldPtrAnonymousHeadStringTagFloat32NPtr  opType = 586
	opStructFieldNPtrHeadFloat32NPtr                   opType = 587
	opStructFieldNPtrHeadOmitEmptyFloat32NPtr          opType = 588
	opStructFieldNPtrHeadStringTagFloat32NPtr          opType = 589
	opStructFieldNPtrAnonymousHeadFloat32NPtr          opType = 590
	opStructFieldNPtrAnonymousHeadOmitEmptyFloat32NPtr opType = 591
	opStructFieldNPtrAnonymousHeadStringTagFloat32NPtr opType = 592
	opStructFieldHeadFloat64NPtr                       opType = 593
	opStructFieldHeadOmitEmptyFloat64NPtr              opType = 594
	opStructFieldHeadStringTagFloat64NPtr              opType = 595
	opStructFieldAnonymousHeadFloat64NPtr              opType = 596
	opStructFieldAnonymousHeadOmitEmptyFloat64NPtr     opType = 597
	opStructFieldAnonymousHeadStringTagFloat64NPtr     opType = 598
	opStructFieldPtrHeadFloat64NPtr                    opType = 599
	opStructFieldPtrHeadOmitEmptyFloat64NPtr           opType = 600
	opStructFieldPtrHeadStringTagFloat64NPtr           opType = 601
	opStructFieldPtrAnonymousHeadFloat64NPtr           opType = 602
	opStructFieldPtrAnonymousHeadOmitEmptyFloat64NPtr  opType = 603
	opStructFieldPtrAnonymousHeadStringTagFloat64NPtr  opType = 604
	opStructFieldNPtrHeadFloat64NPtr                   opType = 605
	opStructFieldNPtrHeadOmitEmptyFloat64NPtr          opType = 606
	opStructFieldNPtrHeadStringTagFloat64NPtr          opType = 607
	opStructFieldNPtrAnonymousHeadFloat64NPtr          opType = 608
	opStructFieldNPtrAnonymousHeadOmitEmptyFloat64NPtr opType = 609
	opStructFieldNPtrAnonymousHeadStringTagFloat64NPtr opType = 610
	opStructFieldHeadBoolNPtr                          opType = 611
	opStructFieldHeadOmitEmptyBoolNPtr                 opType = 612
	opStructFieldHeadStringTagBoolNPtr                 opType = 613
	opStructFieldAnonymousHeadBoolNPtr                 opType = 614
	opStructFieldAnonymousHeadOmitEmptyBoolNPtr        opType = 615
	opStructFieldAnonymousHeadStringTagBoolNPtr        opType = 616
	opStructFieldPtrHeadBoolNPtr                       opType = 617
	opStructFieldPtrHeadOmitEmptyBoolNPtr              opType = 618
	opStructFieldPtrHeadStringTagBoolNPtr              opType = 619
	opStructFieldPtrAnonymousHeadBoolNPtr              opType = 620
	opStructFieldPtrAnonymousHeadOmitEmptyBoolNPtr     opType = 621
	opStructFieldPtrAnonymousHeadStringTagBoolNPtr     opType = 622
	opStructFieldNPtrHeadBoolNPtr                      opType = 623
	opStructFieldNPtrHeadOmitEmptyBoolNPtr             opType = 624
	opStructFieldNPtrHeadStringTagBoolNPtr             opType = 625
	opStructFieldNPtrAnonymousHeadBoolNPtr             opType = 626
	opStructFieldNPtrAnonymousHeadOmitEmptyBoolNPtr    opType = 627
	opStructFieldNPtrAnonymousHeadStringTagBoolNPtr    opType = 628
	opStructFieldHeadStringNPtr                        opType = 629
	opStructFieldHeadOmitEmptyStringNPtr               opType = 630
	opStructFieldHeadStringTagStringNPtr               opType = 631
	opStructFieldAnonymousHeadStringNPtr               opType = 632
	opStructFieldAnonymousHeadOmitEmptyStringNPtr      opType = 633
	opStructFieldAnonymousHeadStringTagStringNPtr      opType = 634
	opStructFieldPtrHeadStringNPtr                     opType = 635
	opStructFieldPtrHeadOmitEmptyStringNPtr            opType = 636
	opStructFieldPtrHeadStringTagStringNPtr            opType = 637
	opStructFieldPtrAnonymousHeadStringNPtr            opType = 638
	opStructFieldPtrAnonymousHeadOmitEmptyStringNPtr   opType = 639
	opStructFieldPtrAnonymousHeadStringTagStringNPtr   opType = 640
	opStructFieldNPtrHeadStringNPtr                    opType = 641
	opStructFieldNPtrHeadOmitEmptyStringNPtr           opType = 642
	opStructFieldNPtrHeadStringTagStringNPtr           opType = 643
	opStructFieldNPtrAnonymousHeadStringNPtr           opType = 644
	opStructFieldNPtrAnonymousHeadOmitEmptyStringNPtr  opType = 645
	opStructFieldNPtrAnonymousHeadStringTagStringNPtr  opType = 646
	opStructFieldHeadBytesNPtr                         opType = 647
	opStructFieldHeadOmitEmptyBytesNPtr                opType = 648
	opStructFieldHeadStringTagBytesNPtr                opType = 649
	opStructFieldAnonymousHeadBytesNPtr                opType = 650
	opStructFieldAnonymousHeadOmitEmptyBytesNPtr       opType = 651
	opStructFieldAnonymousHeadStringTagBytesNPtr       opType = 652
	opStructFieldPtrHeadBytesNPtr                      opType = 653
	opStructFieldPtrHeadOmitEmptyBytesNPtr             opType = 654
	opStructFieldPtrHeadStringTagBytesNPtr             opType = 655
	opStructFieldPtrAnonymousHeadBytesNPtr             opType = 656
	opStructFieldPtrAnonymousHeadOmitEmptyBytesNPtr    opType = 657
	opStructFieldPtrAnonymousHeadStringTagBytesNPtr    opType = 658
	opStructFieldNPtrHeadBytesNPtr                     opType = 659
	opStructFieldNPtrHeadOmitEmptyBytesNPtr            opType = 660
	opStructFieldNPtrHeadStringTagBytesNPtr            opType = 661
	opStructFieldNPtrAnonymousHeadBytesNPtr            opType = 662
	opStructFieldNPtrAnonymousHeadOmitEmptyBytesNPtr   opType = 663
	opStructFieldNPtrAnonymousHeadStringTagBytesNPtr   opType = 664
	opStructFieldHead                                  opType = 665
	opStructFieldHeadOmitEmpty                         opType = 666
	opStructFieldHeadStringTag                         opType = 667
	opStructFieldAnonymousHead                         opType = 668
	opStructFieldAnonymousHeadOmitEmpty                opType = 669
	opStructFieldAnonymousHeadStringTag                opType = 670
	opStructFieldPtrHead                               opType = 671
	opStructFieldPtrHeadOmitEmpty                      opType = 672
	opStructFieldPtrHeadStringTag                      opType = 673
	opStructFieldPtrAnonymousHead                      opType = 674
	opStructFieldPtrAnonymousHeadOmitEmpty             opType = 675
	opStructFieldPtrAnonymousHeadStringTag             opType = 676
	opStructFieldNPtrHead                              opType = 677
	opStructFieldNPtrHeadOmitEmpty                     opType = 678
	opStructFieldNPtrHeadStringTag                     opType = 679
	opStructFieldNPtrAnonymousHead                     opType = 680
	opStructFieldNPtrAnonymousHeadOmitEmpty            opType = 681
	opStructFieldNPtrAnonymousHeadStringTag            opType = 682
	opStructFieldInt                                   opType = 683
	opStructFieldOmitEmptyInt                          opType = 684
	opStructFieldStringTagInt                          opType = 685
	opStructFieldUint                                  opType = 686
	opStructFieldOmitEmptyUint                         opType = 687
	opStructFieldStringTagUint                         opType = 688
	opStructFieldFloat32                               opType = 689
	opStructFieldOmitEmptyFloat32                      opType = 690
	opStructFieldStringTagFloat32                      opType = 691
	opStructFieldFloat64                               opType = 692
	opStructFieldOmitEmptyFloat64                      opType = 693
	opStructFieldStringTagFloat64                      opType = 694
	opStructFieldBool                                  opType = 695
	opStructFieldOmitEmptyBool                         opType = 696
	opStructFieldStringTagBool                         opType = 697
	opStructFieldString                                opType = 698
	opStructFieldOmitEmptyString                       opType = 699
	opStructFieldStringTagString                       opType = 700
	opStructFieldBytes                                 opType = 701
	opStructFieldOmitEmptyBytes                        opType = 702
	opStructFieldStringTagBytes                        opType = 703
	opStructFieldArray                                 opType = 704
	opStructFieldOmitEmptyArray                        opType = 705
	opStructFieldStringTagArray                        opType = 706
	opStructFieldMap                                   opType = 707
	opStructFieldOmitEmptyMap                          opType = 708
	opStructFieldStringTagMap                          opType = 709
	opStructFieldMapLoad                               opType = 710
	opStructFieldOmitEmptyMapLoad                      opType = 711
	opStructFieldStringTagMapLoad                      opType = 712
	opStructFieldSlice                                 opType = 713
	opStructFieldOmitEmptySlice                        opType = 714
	opStructFieldStringTagSlice                        opType = 715
	opStructFieldStruct                                opType = 716
	opStructFieldOmitEmptyStruct                       opType = 717
	opStructFieldStringTagStruct                       opType = 718
	opStructFieldMarshalJSON                           opType = 719
	opStructFieldOmitEmptyMarshalJSON                  opType = 720
	opStructFieldStringTagMarshalJSON                  opType = 721
	opStructFieldMarshalText                           opType = 722
	opStructFieldOmitEmptyMarshalText                  opType = 723
	opStructFieldStringTagMarshalText                  opType = 724
	opStructFieldRecursive                             opType = 725
	opStructFieldOmitEmptyRecursive                    opType = 726
	opStructFieldStringTagRecursive                    opType = 727
	opStructFieldIntString                             opType = 728
	opStructFieldOmitEmptyIntString                    opType = 729
	opStructFieldStringTagIntString                    opType = 730
	opStructFieldUintString                            opType = 731
	opStructFieldOmitEmptyUintString                   opType = 732
	opStructFieldStringTagUintString                   opType = 733
	opStructFieldIntPtr                                opType = 734
	opStructFieldOmitEmptyIntPtr                       opType = 735
	opStructFieldStringTagIntPtr                       opType = 736
	opStructFieldUintPtr                               opType = 737
	opStructFieldOmitEmptyUintPtr                      opType = 738
	opStructFieldStringTagUintPtr                      opType = 739
	opStructFieldFloat32Ptr                            opType = 740
	opStructFieldOmitEmptyFloat32Ptr                   opType = 741
	opStructFieldStringTagFloat32Ptr                   opType = 742
	opStructFieldFloat64Ptr                            opType = 743
	opStructFieldOmitEmptyFloat64Ptr                   opType = 744
	opStructFieldStringTagFloat64Ptr                   opType = 745
	opStructFieldBoolPtr                               opType = 746
	opStructFieldOmitEmptyBoolPtr                      opType = 747
	opStructFieldStringTagBoolPtr                      opType = 748
	opStructFieldStringPtr                             opType = 749
	opStructFieldOmitEmptyStringPtr                    opType = 750
	opStructFieldStringTagStringPtr                    opType = 751
	opStructFieldBytesPtr                              opType = 752
	opStructFieldOmitEmptyBytesPtr                     opType = 753
	opStructFieldStringTagBytesPtr                     opType = 754
	opStructFieldArrayPtr                              opType = 755
	opStructFieldOmitEmptyArrayPtr                     opType = 756
	opStructFieldStringTagArrayPtr                     opType = 757
	opStructFieldSlicePtr                              opType = 758
	opStructFieldOmitEmptySlicePtr                     opType = 759
	opStructFieldStringTagSlicePtr                     opType = 760
	opStructFieldMapPtr                                opType = 761
	opStructFieldOmitEmptyMapPtr                       opType = 762
	opStructFieldStringTagMapPtr                       opType = 763
	opStructFieldIntNPtr                               opType = 764
	opStructFieldOmitEmptyIntNPtr                      opType = 765
	opStructFieldStringTagIntNPtr                      opType = 766
	opStructFieldUintNPtr                              opType = 767
	opStructFieldOmitEmptyUintNPtr                     opType = 768
	opStructFieldStringTagUintNPtr                     opType = 769
	opStructFieldFloat32NPtr                           opType = 770
	opStructFieldOmitEmptyFloat32NPtr                  opType = 771
	opStructFieldStringTagFloat32NPtr                  opType = 772
	opStructFieldFloat64NPtr                           opType = 773
	opStructFieldOmitEmptyFloat64NPtr                  opType = 774
	opStructFieldStringTagFloat64NPtr                  opType = 775
	opStructFieldBoolNPtr                              opType = 776
	opStructFieldOmitEmptyBoolNPtr                     opType = 777
	opStructFieldStringTagBoolNPtr                     opType = 778
	opStructFieldStringNPtr                            opType = 779
	opStructFieldOmitEmptyStringNPtr                   opType = 780
	opStructFieldStringTagStringNPtr                   opType = 781
	opStructFieldBytesNPtr                             opType = 782
	opStructFieldOmitEmptyBytesNPtr                    opType = 783
	opStructFieldStringTagBytesNPtr                    opType = 784
	opStructField                                      opType = 785
	opStructFieldOmitEmpty                             opType = 786
	opStructFieldStringTag                             opType = 787
	opStructEndInt                                     opType = 788
	opStructEndOmitEmptyInt                            opType = 789
	opStructEndStringTagInt                            opType = 790
	opStructEndUint                                    opType = 791
	opStructEndOmitEmptyUint                           opType = 792
	opStructEndStringTagUint                           opType = 793
	opStructEndFloat32                                 opType = 794
	opStructEndOmitEmptyFloat32                        opType = 795
	opStructEndStringTagFloat32                        opType = 796
	opStructEndFloat64                                 opType = 797
	opStructEndOmitEmptyFloat64                        opType = 798
	opStructEndStringTagFloat64                        opType = 799
	opStructEndBool                                    opType = 800
	opStructEndOmitEmptyBool                           opType = 801
	opStructEndStringTagBool                           opType = 802
	opStructEndString                                  opType = 803
	opStructEndOmitEmptyString                         opType = 804
	opStructEndStringTagString                         opType = 805
	opStructEndBytes                                   opType = 806
	opStructEndOmitEmptyBytes                          opType = 807
	opStructEndStringTagBytes                          opType = 808
	opStructEndArray                                   opType = 809
	opStructEndOmitEmptyArray                          opType = 810
	opStructEndStringTagArray                          opType = 811
	opStructEndMap                                     opType = 812
	opStructEndOmitEmptyMap                            opType = 813
	opStructEndStringTagMap                            opType = 814
	opStructEndMapLoad                                 opType = 815
	opStructEndOmitEmptyMapLoad                        opType = 816
	opStructEndStringTagMapLoad                        opType = 817
	opStructEndSlice                                   opType = 818
	opStructEndOmitEmptySlice                          opType = 819
	opStructEndStringTagSlice                          opType = 820
	opStructEndStruct                                  opType = 821
	opStructEndOmitEmptyStruct                         opType = 822
	opStructEndStringTagStruct                         opType = 823
	opStructEndMarshalJSON                             opType = 824
	opStructEndOmitEmptyMarshalJSON                    opType = 825
	opStructEndStringTagMarshalJSON                    opType = 826
	opStructEndMarshalText                             opType = 827
	opStructEndOmitEmptyMarshalText                    opType = 828
	opStructEndStringTagMarshalText                    opType = 829
	opStructEndRecursive                               opType = 830
	opStructEndOmitEmptyRecursive                      opType = 831
	opStructEndStringTagRecursive                      opType = 832
	opStructEndIntString                               opType = 833
	opStructEndOmitEmptyIntString                      opType = 834
	opStructEndStringTagIntString                      opType = 835
	opStructEndUintString                              opType = 836
	opStructEndOmitEmptyUintString                     opType = 837
	opStructEndStringTagUintString                     opType = 838
	opStructEndIntPtr                                  opType = 839
	opStructEndOmitEmptyIntPtr                         opType = 840
	opStructEndStringTagIntPtr                         opType = 841
	opStructEndUintPtr                                 opType = 842
	opStructEndOmitEmptyUintPtr                        opType = 843
	opStructEndStringTagUintPtr                        opType = 844
	opStructEndFloat32Ptr                              opType = 845
	opStructEndOmitEmptyFloat32Ptr                     opType = 846
	opStructEndStringTagFloat32Ptr                     opType = 847
	opStructEndFloat64Ptr                              opType = 848
	opStructEndOmitEmptyFloat64Ptr                     opType = 849
	opStructEndStringTagFloat64Ptr                     opType = 850
	opStructEndBoolPtr                                 opType = 851
	opStructEndOmitEmptyBoolPtr                        opType = 852
	opStructEndStringTagBoolPtr                        opType = 853
	opStructEndStringPtr                               opType = 854
	opStructEndOmitEmptyStringPtr                      opType = 855
	opStructEndStringTagStringPtr                      opType = 856
	opStructEndBytesPtr                                opType = 857
	opStructEndOmitEmptyBytesPtr                       opType = 858
	opStructEndStringTagBytesPtr                       opType = 859
	opStructEndArrayPtr                                opType = 860
	opStructEndOmitEmptyArrayPtr                       opType = 861
	opStructEndStringTagArrayPtr                       opType = 862
	opStructEndSlicePtr                                opType = 863
	opStructEndOmitEmptySlicePtr                       opType = 864
	opStructEndStringTagSlicePtr                       opType = 865
	opStructEndMapPtr                                  opType = 866
	opStructEndOmitEmptyMapPtr                         opType = 867
	opStructEndStringTagMapPtr                         opType = 868
	opStructEndIntNPtr                                 opType = 869
	opStructEndOmitEmptyIntNPtr                        opType = 870
	opStructEndStringTagIntNPtr                        opType = 871
	opStructEndUintNPtr                                opType = 872
	opStructEndOmitEmptyUintNPtr                       opType = 873
	opStructEndStringTagUintNPtr                       opType = 874
	opStructEndFloat32NPtr                             opType = 875
	opStructEndOmitEmptyFloat32NPtr                    opType = 876
	opStructEndStringTagFloat32NPtr                    opType = 877
	opStructEndFloat64NPtr                             opType = 878
	opStructEndOmitEmptyFloat64NPtr                    opType = 879
	opStructEndStringTagFloat64NPtr                    opType = 880
	opStructEndBoolNPtr                                opType = 881
	opStructEndOmitEmptyBoolNPtr                       opType = 882
	opStructEndStringTagBoolNPtr                       opType = 883
	opStructEndStringNPtr                              opType = 884
	opStructEndOmitEmptyStringNPtr                     opType = 885
	opStructEndStringTagStringNPtr                     opType = 886
	opStructEndBytesNPtr                               opType = 887
	opStructEndOmitEmptyBytesNPtr                      opType = 888
	opStructEndStringTagBytesNPtr                      opType = 889
	opStructEnd                                        opType = 890
	opStructEndOmitEmpty                               opType = 891
	opStructEndStringTag                               opType = 892
)

func (t opType) String() string {
	if int(t) >= 893 {
		return ""
	}
	return opTypeStrings[int(t)]
}

func (t opType) codeType() codeType {
	if strings.Contains(t.String(), "Struct") {
		if strings.Contains(t.String(), "End") {
			return codeStructEnd
		}
		return codeStructField
	}
	if strings.Contains(t.String(), "ArrayHead") {
		return codeArrayHead
	}
	if strings.Contains(t.String(), "ArrayElem") {
		return codeArrayElem
	}
	if strings.Contains(t.String(), "SliceHead") {
		return codeSliceHead
	}
	if strings.Contains(t.String(), "SliceElem") {
		return codeSliceElem
	}
	if strings.Contains(t.String(), "MapHead") {
		return codeMapHead
	}
	if strings.Contains(t.String(), "MapKey") {
		return codeMapKey
	}
	if strings.Contains(t.String(), "MapValue") {
		return codeMapValue
	}
	if strings.Contains(t.String(), "MapEnd") {
		return codeMapEnd
	}

	return codeOp
}

func (t opType) headToPtrHead() opType {
	if strings.Index(t.String(), "PtrHead") > 0 {
		return t
	}
	if strings.Index(t.String(), "PtrAnonymousHead") > 0 {
		return t
	}

	idx := strings.Index(t.String(), "Field")
	if idx == -1 {
		return t
	}
	suffix := "Ptr" + t.String()[idx+len("Field"):]

	const toPtrOffset = 6
	if strings.Contains(opType(int(t)+toPtrOffset).String(), suffix) {
		return opType(int(t) + toPtrOffset)
	}
	return t
}

func (t opType) headToNPtrHead() opType {
	if strings.Index(t.String(), "PtrHead") > 0 {
		return t
	}
	if strings.Index(t.String(), "PtrAnonymousHead") > 0 {
		return t
	}

	idx := strings.Index(t.String(), "Field")
	if idx == -1 {
		return t
	}
	suffix := "NPtr" + t.String()[idx+len("Field"):]

	const toPtrOffset = 12
	if strings.Contains(opType(int(t)+toPtrOffset).String(), suffix) {
		return opType(int(t) + toPtrOffset)
	}
	return t
}

func (t opType) headToAnonymousHead() opType {
	const toAnonymousOffset = 3
	if strings.Contains(opType(int(t)+toAnonymousOffset).String(), "Anonymous") {
		return opType(int(t) + toAnonymousOffset)
	}
	return t
}

func (t opType) headToOmitEmptyHead() opType {
	const toOmitEmptyOffset = 1
	if strings.Contains(opType(int(t)+toOmitEmptyOffset).String(), "OmitEmpty") {
		return opType(int(t) + toOmitEmptyOffset)
	}

	return t
}

func (t opType) headToStringTagHead() opType {
	const toStringTagOffset = 2
	if strings.Contains(opType(int(t)+toStringTagOffset).String(), "StringTag") {
		return opType(int(t) + toStringTagOffset)
	}
	return t
}

func (t opType) ptrHeadToHead() opType {
	idx := strings.Index(t.String(), "Ptr")
	if idx == -1 {
		return t
	}
	suffix := t.String()[idx+len("Ptr"):]

	const toPtrOffset = 6
	if strings.Contains(opType(int(t)-toPtrOffset).String(), suffix) {
		return opType(int(t) - toPtrOffset)
	}
	return t
}

func (t opType) fieldToEnd() opType {
	switch t {
	case opStructFieldInt:
		return opStructEndInt
	case opStructFieldOmitEmptyInt:
		return opStructEndOmitEmptyInt
	case opStructFieldStringTagInt:
		return opStructEndStringTagInt
	case opStructFieldUint:
		return opStructEndUint
	case opStructFieldOmitEmptyUint:
		return opStructEndOmitEmptyUint
	case opStructFieldStringTagUint:
		return opStructEndStringTagUint
	case opStructFieldFloat32:
		return opStructEndFloat32
	case opStructFieldOmitEmptyFloat32:
		return opStructEndOmitEmptyFloat32
	case opStructFieldStringTagFloat32:
		return opStructEndStringTagFloat32
	case opStructFieldFloat64:
		return opStructEndFloat64
	case opStructFieldOmitEmptyFloat64:
		return opStructEndOmitEmptyFloat64
	case opStructFieldStringTagFloat64:
		return opStructEndStringTagFloat64
	case opStructFieldBool:
		return opStructEndBool
	case opStructFieldOmitEmptyBool:
		return opStructEndOmitEmptyBool
	case opStructFieldStringTagBool:
		return opStructEndStringTagBool
	case opStructFieldString:
		return opStructEndString
	case opStructFieldOmitEmptyString:
		return opStructEndOmitEmptyString
	case opStructFieldStringTagString:
		return opStructEndStringTagString
	case opStructFieldBytes:
		return opStructEndBytes
	case opStructFieldOmitEmptyBytes:
		return opStructEndOmitEmptyBytes
	case opStructFieldStringTagBytes:
		return opStructEndStringTagBytes
	case opStructFieldMarshalJSON:
		return opStructEndMarshalJSON
	case opStructFieldOmitEmptyMarshalJSON:
		return opStructEndOmitEmptyMarshalJSON
	case opStructFieldStringTagMarshalJSON:
		return opStructEndStringTagMarshalJSON
	case opStructFieldMarshalText:
		return opStructEndMarshalText
	case opStructFieldOmitEmptyMarshalText:
		return opStructEndOmitEmptyMarshalText
	case opStructFieldStringTagMarshalText:
		return opStructEndStringTagMarshalText
	case opStructFieldIntString:
		return opStructEndIntString
	case opStructFieldOmitEmptyIntString:
		return opStructEndOmitEmptyIntString
	case opStructFieldStringTagIntString:
		return opStructEndStringTagIntString
	case opStructFieldUintString:
		return opStructEndUintString
	case opStructFieldOmitEmptyUintString:
		return opStructEndOmitEmptyUintString
	case opStructFieldStringTagUintString:
		return opStructEndStringTagUintString
	case opStructFieldIntPtr:
		return opStructEndIntPtr
	case opStructFieldOmitEmptyIntPtr:
		return opStructEndOmitEmptyIntPtr
	case opStructFieldStringTagIntPtr:
		return opStructEndStringTagIntPtr
	case opStructFieldUintPtr:
		return opStructEndUintPtr
	case opStructFieldOmitEmptyUintPtr:
		return opStructEndOmitEmptyUintPtr
	case opStructFieldStringTagUintPtr:
		return opStructEndStringTagUintPtr
	case opStructFieldFloat32Ptr:
		return opStructEndFloat32Ptr
	case opStructFieldOmitEmptyFloat32Ptr:
		return opStructEndOmitEmptyFloat32Ptr
	case opStructFieldStringTagFloat32Ptr:
		return opStructEndStringTagFloat32Ptr
	case opStructFieldFloat64Ptr:
		return opStructEndFloat64Ptr
	case opStructFieldOmitEmptyFloat64Ptr:
		return opStructEndOmitEmptyFloat64Ptr
	case opStructFieldStringTagFloat64Ptr:
		return opStructEndStringTagFloat64Ptr
	case opStructFieldBoolPtr:
		return opStructEndBoolPtr
	case opStructFieldOmitEmptyBoolPtr:
		return opStructEndOmitEmptyBoolPtr
	case opStructFieldStringTagBoolPtr:
		return opStructEndStringTagBoolPtr
	case opStructFieldStringPtr:
		return opStructEndStringPtr
	case opStructFieldOmitEmptyStringPtr:
		return opStructEndOmitEmptyStringPtr
	case opStructFieldStringTagStringPtr:
		return opStructEndStringTagStringPtr
	case opStructFieldBytesPtr:
		return opStructEndBytesPtr
	case opStructFieldOmitEmptyBytesPtr:
		return opStructEndOmitEmptyBytesPtr
	case opStructFieldStringTagBytesPtr:
		return opStructEndStringTagBytesPtr
	case opStructFieldArrayPtr:
		return opStructEndArrayPtr
	case opStructFieldOmitEmptyArrayPtr:
		return opStructEndOmitEmptyArrayPtr
	case opStructFieldStringTagArrayPtr:
		return opStructEndStringTagArrayPtr
	case opStructFieldSlicePtr:
		return opStructEndSlicePtr
	case opStructFieldOmitEmptySlicePtr:
		return opStructEndOmitEmptySlicePtr
	case opStructFieldStringTagSlicePtr:
		return opStructEndStringTagSlicePtr
	case opStructFieldMapPtr:
		return opStructEndMapPtr
	case opStructFieldOmitEmptyMapPtr:
		return opStructEndOmitEmptyMapPtr
	case opStructFieldStringTagMapPtr:
		return opStructEndStringTagMapPtr
	case opStructFieldIntNPtr:
		return opStructEndIntNPtr
	case opStructFieldOmitEmptyIntNPtr:
		return opStructEndOmitEmptyIntNPtr
	case opStructFieldStringTagIntNPtr:
		return opStructEndStringTagIntNPtr
	case opStructFieldUintNPtr:
		return opStructEndUintNPtr
	case opStructFieldOmitEmptyUintNPtr:
		return opStructEndOmitEmptyUintNPtr
	case opStructFieldStringTagUintNPtr:
		return opStructEndStringTagUintNPtr
	case opStructFieldFloat32NPtr:
		return opStructEndFloat32NPtr
	case opStructFieldOmitEmptyFloat32NPtr:
		return opStructEndOmitEmptyFloat32NPtr
	case opStructFieldStringTagFloat32NPtr:
		return opStructEndStringTagFloat32NPtr
	case opStructFieldFloat64NPtr:
		return opStructEndFloat64NPtr
	case opStructFieldOmitEmptyFloat64NPtr:
		return opStructEndOmitEmptyFloat64NPtr
	case opStructFieldStringTagFloat64NPtr:
		return opStructEndStringTagFloat64NPtr
	case opStructFieldBoolNPtr:
		return opStructEndBoolNPtr
	case opStructFieldOmitEmptyBoolNPtr:
		return opStructEndOmitEmptyBoolNPtr
	case opStructFieldStringTagBoolNPtr:
		return opStructEndStringTagBoolNPtr
	case opStructFieldStringNPtr:
		return opStructEndStringNPtr
	case opStructFieldOmitEmptyStringNPtr:
		return opStructEndOmitEmptyStringNPtr
	case opStructFieldStringTagStringNPtr:
		return opStructEndStringTagStringNPtr
	case opStructFieldBytesNPtr:
		return opStructEndBytesNPtr
	case opStructFieldOmitEmptyBytesNPtr:
		return opStructEndOmitEmptyBytesNPtr
	case opStructFieldStringTagBytesNPtr:
		return opStructEndStringTagBytesNPtr
	}
	return t
}

func (t opType) fieldToOmitEmptyField() opType {
	const toOmitEmptyOffset = 1
	if strings.Contains(opType(int(t)+toOmitEmptyOffset).String(), "OmitEmpty") {
		return opType(int(t) + toOmitEmptyOffset)
	}
	return t
}

func (t opType) fieldToStringTagField() opType {
	const toStringTagOffset = 2
	if strings.Contains(opType(int(t)+toStringTagOffset).String(), "StringTag") {
		return opType(int(t) + toStringTagOffset)
	}
	return t
}
