package gqlgenserver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/goccy/go-json/examples/graphql/store"
)

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *store.Post, first *int) ([]*store.Comment, error) {
	if loaders := store.LoadersFrom(ctx); loaders != nil {
		comments, err := loaders.CommentsOf.Load(ctx, obj)
		return store.First(comments, first), err
	}
	return store.First(r.Store.CommentsOf([]*store.Post{obj})[0], first), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*store.User, error) {
	r.Store.Fetch()
	return r.Store.User(id), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, first *int) ([]*store.User, error) {
	r.Store.Fetch()
	return store.First(r.Store.Users, first), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first *int) ([]*store.Post, error) {
	r.Store.Fetch()
	return store.First(r.Store.Posts, first), nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, text string, first *int) ([]store.SearchResult, error) {
	r.Store.Fetch()
	return r.Store.Search(text, first), nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *store.User, first *int) ([]*store.Post, error) {
	if loaders := store.LoadersFrom(ctx); loaders != nil {
		posts, err := loaders.PostsOf.Load(ctx, obj)
		return store.First(posts, first), err
	}
	return store.First(r.Store.PostsOf([]*store.User{obj})[0], first), nil
}

// Friends is the resolver for the friends field.
func (r *userResolver) Friends(ctx context.Context, obj *store.User, first *int) ([]*store.User, error) {
	if loaders := store.LoadersFrom(ctx); loaders != nil {
		friends, err := loaders.FriendsOf.Load(ctx, obj)
		return store.First(friends, first), err
	}
	return store.First(r.Store.FriendsOf([]*store.User{obj})[0], first), nil
}

// Secret is the resolver for the secret field.
func (r *userResolver) Secret(ctx context.Context, obj *store.User) (*string, error) {
	return nil, errors.New("the secret of " + obj.ID + " is not readable")
}

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	postResolver  struct{ *Resolver }
	queryResolver struct{ *Resolver }
	userResolver  struct{ *Resolver }
)
