// Package gqlgenserver is the GraphQL server of the example which gqlgen generates, to compare with the one
// built on go-json. It is set up as a production server of gqlgen is: the POST transport and a cache of the
// parsed and validated queries.
//
// generated.go and models_gen.go are generated by `go run github.com/99designs/gqlgen generate --config gqlgen.yml`
// in this directory.
package gqlgenserver

import (
	"net/http"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/handler/lru"
	"github.com/99designs/gqlgen/graphql/handler/transport"
	"github.com/vektah/gqlparser/v2/ast"

	"github.com/goccy/go-json/examples/graphql/store"
)

// NewHandler returns the handler of the GraphQL requests on the store.
func NewHandler(s *store.Store) http.Handler {
	srv := handler.New(NewExecutableSchema(Config{Resolvers: &Resolver{Store: s}}))
	srv.AddTransport(transport.POST{})
	srv.SetQueryCache(lru.New[*ast.QueryDocument](1000))
	return srv
}
