// Package gqlgenserver is the GraphQL server of the example which gqlgen generates, to compare with the one
// built on go-json. It is set up as a production server of gqlgen is: the POST transport, a cache of the
// parsed and validated queries, and data loaders ( dataloadgen, which the documents of gqlgen recommend )
// against the N+1 problem.
//
// generated.go, models_gen.go and schema.resolvers.go are generated by
// `go run github.com/99designs/gqlgen@v0.17.95 generate --config gqlgen.yml` in this directory, which keeps the
// implementations of the resolvers.
package gqlgenserver

import (
	"net/http"
	"time"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/handler/lru"
	"github.com/99designs/gqlgen/graphql/handler/transport"
	"github.com/vektah/gqlparser/v2/ast"

	"github.com/goccy/go-json/examples/graphql/store"
)

// Options are how the server resolves the fields.
type Options struct {
	// LoaderWait is how long the data loaders of a request wait for the keys of a batch, or 0 if the resolvers
	// fetch by themselves, one fetch each.
	LoaderWait time.Duration
}

// NewHandler returns the handler of the GraphQL requests on the store.
func NewHandler(s *store.Store, opts Options) http.Handler {
	srv := handler.New(NewExecutableSchema(Config{Resolvers: &Resolver{Store: s}}))
	srv.AddTransport(transport.POST{})
	srv.SetQueryCache(lru.New[*ast.QueryDocument](1000))
	if opts.LoaderWait == 0 {
		return srv
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := store.WithLoaders(r.Context(), s.NewLoaders(opts.LoaderWait))
		srv.ServeHTTP(w, r.WithContext(ctx))
	})
}
